## WEB SCRAPING – ASSIGNMENT - 4



#### Importing the required Libraries

In [1]:
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re

In [3]:
# Loading the web driver

driver=webdriver.Chrome("chromedriver.exe")

#### Q. No. 1 :- Scrape the details of most viewed videos on YouTube from Wikipedia:
- Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/
- You need to find following details:
    - Rank
    - Name
    - Artist
    - Upload date
    - Views

In [40]:
# Loading the web-page

url1 = 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url1)

In [60]:
# Creating empty list

rank_youtube = []
name_youtube = []
artist_youtube = []
upload_date = []
views_youtube = []

In [57]:
# Scraping rank
data1 =[]
rank_tag1 = driver.find_elements_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr/td')
for r in rank_tag1:
    try:
        data1.append(r.text)
    except NoSuchElementException:
        data1.append('-')
data1

['1.',
 '"Baby Shark Dance"[22]',
 "Pinkfong Kids' Songs & Stories",
 '9.06',
 'June 17, 2016',
 '[B]',
 '2.',
 '"Despacito"[24]',
 'Luis Fonsi',
 '7.47',
 'January 12, 2017',
 '[C]',
 '3.',
 '"Johny Johny Yes Papa"[25]',
 'LooLoo Kids',
 '5.60',
 'October 8, 2016',
 '[D]',
 '4.',
 '"Shape of You"[26]',
 'Ed Sheeran',
 '5.40',
 'January 30, 2017',
 '[E]',
 '5.',
 '"See You Again"[27]',
 'Wiz Khalifa',
 '5.20',
 'April 6, 2015',
 '[F]',
 '6.',
 '"Masha and the Bear – Recipe for Disaster"[30]',
 'Get Movies',
 '4.45',
 'January 31, 2012',
 '[G]',
 '7.',
 '"Bath Song"[31]',
 'Cocomelon – Nursery Rhymes',
 '4.39',
 'May 2, 2018',
 '[H]',
 '8.',
 '"Learning Colors – Colorful Eggs on a Farm"[32]',
 'Miroshka TV',
 '4.35',
 'February 27, 2018',
 '[I]',
 '9.',
 '"Uptown Funk"[33]',
 'Mark Ronson',
 '4.25',
 'November 19, 2014',
 '[J]',
 '10.',
 '"Gangnam Style"[34]',
 'Psy',
 '4.14',
 'July 15, 2012',
 '[K]',
 '11.',
 '"Phonics Song with Two Words"[36]',
 'ChuChu TV',
 '4.04',
 'March 6, 2014',
 '',
 '12.',
 '"Sugar"[37]',
 'Maroon 5',
 '3.52',
 'January 14, 2015',
 '',
 '13.',
 '"Dame Tu Cosita"[38]',
 'El Chombo',
 '3.49',
 'April 5, 2018',
 '',
 '14.',
 '"Sorry"[39]',
 'Justin Bieber',
 '3.45',
 'October 22, 2015',
 '',
 '15.',
 '"Roar"[40]',
 'Katy Perry',
 '3.40',
 'September 5, 2013',
 '',
 '16.',
 '"Counting Stars"[41]',
 'OneRepublic',
 '3.35',
 'May 31, 2013',
 '',
 '17.',
 '"Thinking Out Loud"[42]',
 'Ed Sheeran',
 '3.30',
 'October 7, 2014',
 '',
 '18.',
 '"Wheels on the Bus"[43]',
 'Cocomelon – Nursery Rhymes',
 '3.20',
 'May 24, 2018',
 '',
 '19.',
 '"Dark Horse"[44]',
 'Katy Perry',
 '3.11',
 'February 20, 2014',
 '',
 '20.',
 '"Faded"[45]',
 'Alan Walker',
 '3.11',
 'December 3, 2015',
 '',
 '21.',
 '"Girls Like You"[46]',
 'Maroon 5',
 '3.08',
 'May 31, 2018',
 '',
 '22.',
 '"Shake It Off"[47]',
 'Taylor Swift',
 '3.08',
 'August 18, 2014',
 '',
 '23.',
 '"Lean On"[48]',
 'Major Lazer',
 '3.07',
 'March 22, 2015',
 '',
 '24.',
 '"Bailando"[49]',
 'Enrique Iglesias',
 '3.07',
 'April 11, 2014',
 '',
 '25.',
 '"Let Her Go"[50]',
 'Passenger',
 '3.04',
 'July 25, 2012',
 '',
 '26.',
 '"Mi Gente"[51]',
 'J Balvin',
 '2.95',
 'June 29, 2017',
 '',
 '27.',
 '"Perfect"[52]',
 'Ed Sheeran',
 '2.91',
 'November 9, 2017',
 '',
 '28.',
 '"Axel F"[53]',
 'Crazy Frog',
 '2.91',
 'June 16, 2009',
 '',
 '29.',
 '"Waka Waka (This Time for Africa)"[54]',
 'Shakira',
 '2.90',
 'June 4, 2010',
 '',
 '30.',
 '"Hello"[55]',
 'Adele',
 '2.86',
 'October 22, 2015',
 '']

In [71]:
# Scraping rank
rank_youtube = data1[0::6]
rank_youtube

# Scraping the name of the video
name_youtube = data1[1::6]

#Scraping the Artist name
artist_youtube = data1[2::6]

#Scraping the views
views_youtube = data1[3::6]

#Scraping the date of upload
upload_date = data1[4::6]

# Printing the length of all the columns

print(len(rank_youtube), len(name_youtube), len(artist_youtube), len(views_youtube), len(upload_date))

30 30 30 30 30

In [72]:
# Creating dataframe

youtube = pd.DataFrame({'Rank':rank_youtube, 'Video Name':name_youtube, 'Artist Name':artist_youtube, 
                       'Views Count':views_youtube, 'Upload Date':upload_date})

youtube

,Rank,Video Name,Artist Name,Views Count,Upload Date
0,1.,"""Baby Shark Dance""[22]",Pinkfong Kids' Songs & Stories,9.06,"June 17, 2016"
1,2.,"""Despacito""[24]",Luis Fonsi,7.47,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[25]",LooLoo Kids,5.60,"October 8, 2016"
3,4.,"""Shape of You""[26]",Ed Sheeran,5.40,"January 30, 2017"
4,5.,"""See You Again""[27]",Wiz Khalifa,5.20,"April 6, 2015"
5,6.,"""Masha and the Bear – Recipe for Disaster""[30]",Get Movies,4.45,"January 31, 2012"
6,7.,"""Bath Song""[31]",Cocomelon – Nursery Rhymes,4.39,"May 2, 2018"
7,8.,"""Learning Colors – Colorful Eggs on a Farm""[32]",Miroshka TV,4.35,"February 27, 2018"
8,9.,"""Uptown Funk""[33]",Mark Ronson,4.25,"November 19, 2014"
9,10.,"""Gangnam Style""[34]",Psy,4.14,"July 15, 2012"
10,11.,"""Phonics Song with Two Words""[36]",ChuChu TV,4.04,"March 6, 2014"
11,12.,"""Sugar""[37]",Maroon 5,3.52,"January 14, 2015"
12,13.,"""Dame Tu Cosita""[38]",El Chombo,3.49,"April 5, 2018"
13,14.,"""Sorry""[39]",Justin Bieber,3.45,"October 22, 2015"
14,15.,"""Roar""[40]",Katy Perry,3.40,"September 5, 2013"
15,16.,"""Counting Stars""[41]",OneRepublic,3.35,"May 31, 2013"
16,17.,"""Thinking Out Loud""[42]",Ed Sheeran,3.30,"October 7, 2014"
17,18.,"""Wheels on the Bus""[43]",Cocomelon – Nursery Rhymes,3.20,"May 24, 2018"
18,19.,"""Dark Horse""[44]",Katy Perry,3.11,"February 20, 2014"
19,20.,"""Faded""[45]",Alan Walker,3.11,"December 3, 2015"
20,21.,"""Girls Like You""[46]",Maroon 5,3.08,"May 31, 2018"
21,22.,"""Shake It Off""[47]",Taylor Swift,3.08,"August 18, 2014"
22,23.,"""Lean On""[48]",Major Lazer,3.07,"March 22, 2015"
23,24.,"""Bailando""[49]",Enrique Iglesias,3.07,"April 11, 2014"
24,25.,"""Let Her Go""[50]",Passenger,3.04,"July 25, 2012"
25,26.,"""Mi Gente""[51]",J Balvin,2.95,"June 29, 2017"
26,27.,"""Perfect""[52]",Ed Sheeran,2.91,"November 9, 2017"
27,28.,"""Axel F""[53]",Crazy Frog,2.91,"June 16, 2009"
28,29.,"""Waka Waka (This Time for Africa)""[54]",Shakira,2.90,"June 4, 2010"
29,30.,"""Hello""[55]",Adele,2.86,"October 22, 2015"

------------------------------------------------------------------------------------------------------------------------------

#### Q. No. 2:-
- Scrape the details team India’s international fixtures from bcci.tv.
- Url = https://www.bcci.tv/.
- You need to find following details:
    - Match title (I.e. 1st ODI)
    - Series
    - Place
    - Date
    - Time
#### Note: - 
From bcci.tv home page you have reach to the international fixture page through code.

In [47]:
# Loading the web driver

driver=webdriver.Chrome("chromedriver.exe")

In [48]:
# Loading the web-page

url2 = 'https://www.bcci.tv/'

driver.get(url2)

In [17]:
# Visiting the international fixture page.

fix_tag = driver.find_element_by_xpath('//div[@class="navigation__drop-down drop-down drop-down--reveal-on-hover"]')

fix_tag.click()

fix_tag2 = driver.find_element_by_xpath('//a[@class="navigation__link navigation__link--in-drop-down"]')
fix_tag2.click()

In [18]:
# Creating empty list
match_urls = []
match_title = []
series = []
place_match = []
date_match = []
time_match = []

In [19]:
# Scraping URLs

mtch_url = driver.find_elements_by_xpath('//a[@class="js-match event-list__item event-list-item fixture  t-test fixture--long event-list-item--long"]')

for u in mtch_url:
    match_urls.append(u.get_attribute('href'))
match_urls

['https://www.bcci.tv/events/22435/england-v-india-2021/match/22436/1st-test?tab=overview',
 'https://www.bcci.tv/events/22435/england-v-india-2021/match/22437/2nd-test?tab=overview',
 'https://www.bcci.tv/events/22435/england-v-india-2021/match/22438/3rd-test?tab=overview',
 'https://www.bcci.tv/events/22435/england-v-india-2021/match/22439/4th-test?tab=overview',
 'https://www.bcci.tv/events/22435/england-v-india-2021/match/22440/5th-test?tab=overview']

In [20]:
# Scraping the match title
mth = driver.find_elements_by_xpath('//strong[@class="fixture__name fixture__name--with-margin"]')
for m in mth:
    try:
        match_title.append(m.text)
    except NoSuchElementException:
        match_title.append('--')
time.sleep(5)

# Scraping the series name
ser = driver.find_elements_by_xpath('//span[@class="u-unskewed-text fixture__tournament-label u-truncated"]')
for s in ser:
    try:
        series.append(s.text)
    except NoSuchElementException:
        series.append('--')

time.sleep(5)

# Scraping the match place

plc = driver.find_elements_by_xpath('//p[@class="fixture__additional-info"]//span')
for p in plc:
    try:
        place_match.append(p.text)
    except NoSuchElementException:
        place_match.append('--')
        
time.sleep(5)

# Scraping match time
tim_tag = driver.find_elements_by_xpath('//span[@class="fixture__time"]')
for t in tim_tag:
    try:
        time_match.append(t.text)
    except NoSuchElementException:
        time_match.append('--')
time.sleep(5)

# Scraping the match date
for u2 in match_urls:
    driver.get(u2)
    
    dte = driver.find_elements_by_xpath('//div[@class="mc-header-scorebox__datetime"]//strong')
    for d in dte:
        try:
            date_match.append(d.text)
        except NoSuchElementException:
            date_match.append('--')

In [21]:
# Checking the length of the data which we have scraped.

print (len(match_title),len(series),len(place_match),len(time_match),len(date_match))

5 5 5 5 5

In [24]:
# Making dataframe:

fixtures = pd.DataFrame({})

fixtures['Match Title'] = match_title
fixtures['Series'] = series
fixtures['Place'] = place_match
fixtures['Date'] = date_match
fixtures['Time'] = time_match

fixtures

,Match Title,Series,Place,Date,Time
0,1st Test,ENGLAND V INDIA 2021,"Trent Bridge, Nottingham",Wednesday 4 August,15:30 IST
1,2nd Test,ENGLAND V INDIA 2021,"Lord's, London",Thursday 12 August,15:30 IST
2,3rd Test,ENGLAND V INDIA 2021,"Headingley, Leeds",Wednesday 25 August,15:30 IST
3,4th Test,ENGLAND V INDIA 2021,"The Oval, London",Thursday 2 September,15:30 IST
4,5th Test,ENGLAND V INDIA 2021,"Old Trafford, Manchester",Friday 10 September,15:30 IST

-----------------------------------------------------------------------------------------------------------------------------

#### Q. No. 3:-
- Scrape the details of selenium exception from guru99.com.
    - Url = https://www.guru99.com/
- You need to find following details:
    - Name
    - Description
#### Note:- 
From guru99 home page you have to reach to selenium exception handling page through code.

In [49]:
# Loading the web driver

driver=webdriver.Chrome("chromedriver.exe")

In [50]:
# Loading the web-page.

url3 = 'https://www.guru99.com/'
driver.get(url3)

In [52]:
# Clicking on the 'Selenium'

selenium_tag3 = driver.find_element_by_xpath('//*[@id="g-footer"]/div/div[1]/div/div/div/div/div/div[4]/div[2]/div/div/div/h4/a')
selenium_tag3.click()

In [53]:
# Visiting the 'Selenium Exception Handling page'

selenium_exp = driver.find_element_by_xpath('//*[@id="g-mainbar"]/div/div/div/div/div/div/div[2]/table[5]/tbody/tr[34]/td[1]/a')
selenium_exp.click()

In [54]:
# Scraping the name of the exception

table_exp = [] # Creating empty list

nme_tag3 = driver.find_elements_by_xpath('//table[@class="table table-striped"]//td')
for n in nme_tag3:
    table_exp.append(n.text)
    
table_exp = table_exp[2:]
table_exp

['ElementNotVisibleException',
 'This type of Selenium exception occurs when an existing element in DOM has a feature set as hidden.',
 'ElementNotSelectableException',
 'This Selenium exception occurs when an element is presented in the DOM, but you can be able to select. Therefore, it is not possible to interact.',
 'NoSuchElementException',
 'This Exception occurs if an element could not be found.',
 'NoSuchFrameException',
 'This Exception occurs if the frame target to be switched to does not exist.',
 'NoAlertPresentException',
 'This Exception occurs when you switch to no presented alert.',
 'NoSuchWindowException',
 'This Exception occurs if the window target to be switch does not exist.',
 'StaleElementReferenceException',
 'This Selenium exception occurs happens when the web element is detached from the current DOM.',
 'SessionNotFoundException',
 'The WebDriver is acting after you quit the browser.',
 'TimeoutException',
 "Thrown when there is not enough time for a command to be completed. For Example, the element searched wasn't found in the specified time.",
 'WebDriverException',
 'This Exception takes place when the WebDriver is acting right after you close the browser.',
 'ConnectionClosedException',
 'This type of Exception takes place when there is a disconnection in the driver.',
 'ElementClickInterceptedException',
 'The command may not be completed as the element receiving the events is concealing the element which was requested clicked.',
 'ElementNotInteractableException',
 'This Selenium exception is thrown when any element is presented in the DOM. However, it is impossible to interact with such an element.',
 'ErrorInResponseException',
 'This happens while interacting with the Firefox extension or the remote driver server.',
 'ErrorHandler.UnknownServerException',
 'Exception is used as a placeholder in case if the server returns an error without a stack trace.',
 'ImeActivationFailedException',
 'This expectation will occur when IME engine activation has failed.',
 'ImeNotAvailableException',
 'It takes place when IME support is unavailable.',
 'InsecureCertificateException',
 'Navigation made the user agent to hit a certificate warning. This can cause by an invalid or expired TLS certificate.',
 'InvalidArgumentException',
 'It occurs when an argument does not belong to the expected type.',
 'InvalidCookieDomainException',
 'This happens when you try to add a cookie under a different domain instead of current URL.',
 'InvalidCoordinatesException',
 'This type of Exception matches an interacting operation that is not valid.',
 'InvalidElementStateExceptio',
 "It occurs when command can't be finished when the element is invalid.",
 'InvalidSessionIdException',
 'This Exception took place when the given session ID is not included in the list of active sessions. It means the session does not exist or is inactive either.',
 'InvalidSwitchToTargetException',
 'This occurs when the frame or window target to be switched does not exist.',
 'JavascriptException',
 'This issue occurs while executing JavaScript given by the user.',
 'JsonException',
 'It occurs when you afford to get the session when the session is not created.',
 'NoSuchAttributeException',
 'This kind of Exception occurs when the attribute of an element could not be found.',
 'MoveTargetOutOfBoundsException',
 'It takes place if the target provided to the ActionChains move() methodology is not valid. For Example, out of the document.',
 'NoSuchContextException',
 'ContextAware does mobile device testing.',
 'NoSuchCookieException',
 'This Exception occurs when no cookie matching with the given pathname found for all the associated cookies of the currently browsing document.',
 'NotFoundException',
 'This Exception is a subclass of WebDriverException. This will occur when an element on the DOM does not exist.',
 'RemoteDriverServerException',
 'This Selenium exception is thrown when the server is not responding because of the problem that the capabilities described are not proper.',
 'ScreenshotException',
 'It is not possible to capture a screen.',
 'SessionNotCreatedException',
 'It happens when a new session could not be successfully created.',
 'UnableToSetCookieException',
 'This occurs if a driver is unable to set a cookie.',
 'UnexpectedTagNameException',
 'Happens if a support class did not get a web element as expected.',
 'UnhandledAlertException',
 'This expectation occurs when there is an alert, but WebDriver is not able to perform Alert operation.',
 'UnexpectedAlertPresentException',
 'It occurs when there is the appearance of an unexpected alert.',
 'UnknownMethodException',
 'This Exception happens when the requested command matches with a known URL but and not matching with a methodology for a specific URL.',
 'UnreachableBrowserException',
 'This Exception occurs only when the browser is not able to be opened or crashed because of some reason.',
 'UnsupportedCommandException',
 "This occurs when remote WebDriver does n't send valid commands as expected."]

In [55]:
# Spitting the data and saving into 'name_exception' and 'description_exception'

name_exception = []
description_exception = []

for ex in range (0, len(table_exp)):
    if ex%2:
        description_exception.append(table_exp[ex])
    else:
        name_exception.append(table_exp[ex])

In [56]:
print(len(name_exception), len(description_exception))

41 41

In [57]:
# Creating the dataframe

exceptions = pd.DataFrame({"Exception Name":name_exception, "Description":description_exception})

exceptions

,Exception Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can't be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

-------------------------------------------------------------------------------------------------------------------------------

#### Q. No. 4:-

- Scrape the details of State-wise GDP of India from statisticstime.com.
    - Url = http://statisticstimes.com/
- You have to find following details:
    - Rank
    - State
    - GSDP at current price (19-20)
    - GSDP at current price (18-19)
    - Share(18-19)
    - GDP($ billion)
    
#### Note:- From statisticstimes home page you have to reach to economy page through code.

In [2]:
# Loading the web driver

driver=webdriver.Chrome("chromedriver.exe")

In [3]:
# Loading the web page
url4 = 'http://statisticstimes.com/'

driver.get(url4)

In [5]:
# Opening the economy page

economy_tag4 = driver.find_element_by_xpath('//*[@id="top"]/div[2]/div[2]/button')
economy_tag4.click()
time.sleep(1)

india_economy = driver.find_element_by_xpath('//*[@id="top"]/div[2]/div[2]/div/a[3]')
india_economy.click()

In [7]:
# Opening the web-page of statewise GDP

state_tag4 = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
state_tag4.click()

In [25]:
# Creating the empty lists

rank_state = []
state_name = []
gsdp_19_20 = []
gsdp_18_19 = []
share_18_19 = []
gdp_billion = []

In [26]:
# Scraping the state rank
rnk_tag4 = driver.find_elements_by_xpath('//td[@class="data1"]')
for r in rnk_tag4:
    try:
        rank_state.append(r.text)
    except NoSuchElementException:
        rank_state.append('--')
time.sleep(5)

rank_state = rank_state[:33]

# Scraping the state names
nme_tag4 = driver.find_elements_by_xpath('//td[@class="name"]')
for n in nme_tag4:
    try:
        state_name.append(n.text)
    except NoSuchElementException:
        state_name.append('--')
time.sleep(5)

state_name = state_name[:33]

# Scraping the GSDP at current Price (19-20), Share (18-19), and GDP ($ Billion)
data4 = []
gsdp_tag4 = driver.find_elements_by_xpath('//td[@class="data"]')
for g in gsdp_tag4:
    try:
        data4.append(g.text)
    except NoSuchElementException:
        data4.append('--')
data4 = data4[:165]
time.sleep(5)

# Scraping GSDP at current price (19-20)
gsdp_19_20 = data4[0::5]
gsdp_19_20
time.sleep(2)

# Scraping Share (18-19)
share_18_19 = data4[1::5]
share_18_19
time.sleep(2)

# Scraping GDP ($ Billion)
gdp_billion = data4[2::5]
gdp_billion
time.sleep(2)

# Scraping the GSDP at current Price (18-19)
gsdp18_tag4 = driver.find_elements_by_xpath('//td[@class="data sorting_1"]')
for g2 in gsdp18_tag4:
    try:
        gsdp_18_19.append(g2.text)
    except NoSuchElementException:
        gsdp_18_19.append('--')
time.sleep(5)

gsdp_18_19 = gsdp_18_19[:33]

In [27]:
print(len(rank_state),len(state_name),len(gsdp_19_20),len(gsdp_18_19),len(share_18_19),len(gdp_billion))

33 33 33 33 33 33

In [28]:
# Creating DataFrame:

GDP = pd.DataFrame({'Rank':rank_state, 'State Name':state_name, 'GSDP at current price (19-20)':gsdp_19_20, 
                    'GSDP at current price (18-19)':gsdp_18_19, 'Share (18-19)':share_18_19, 'GDP ($ Billion)':gdp_billion})

GDP

,Rank,State Name,GSDP at current price (19-20),GSDP at current price (18-19),Share (18-19),GDP ($ Billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

------------------------------------------------------------------------------------------------------------------------------

#### Q. No. 5:-
- Scrape the details of trending repositories on Github.com.
- Url = https://github.com/
- You have to find the following details:
    - Repository title
    - Repository description
    - Contributors count
    - Language used
    
#### Note:- From the home page you have to click on the trending option from Explore menu through code.

In [2]:
# Loading the web driver.

driver=webdriver.Chrome("chromedriver.exe")

In [22]:
# Loading the web-page 

url5 = 'https://github.com/'
driver.get(url5)

In [23]:
# Visiting the trending page
exp_tag5 = driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]')
exp_tag5.click()
time.sleep(2)

trending_tag5 = driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[2]/li[3]/a')
trending_tag5.click()

ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=92.0.4515.131)

In [5]:
# Creating empty list

url_respository = []
respository_title = []
description_respository =[]
count_contributor = []
used_language = []

In [6]:
# Scraping URLs
url_tag5 = driver.find_elements_by_xpath('//h1[@class="h3 lh-condensed"]//a')
for u in url_tag5:
    url_respository.append(u.get_attribute('href'))
url_respository

['https://github.com/Azure/azure-sdk-for-net',
 'https://github.com/SheetJS/sheetjs',
 'https://github.com/0x727/ShuiZe_0x727',
 'https://github.com/OAI/OpenAPI-Specification',
 'https://github.com/microsoft/ML-For-Beginners',
 'https://github.com/apache/apisix',
 'https://github.com/geekxh/hello-algorithm',
 'https://github.com/GhostPack/Rubeus',
 'https://github.com/datafuselabs/datafuse',
 'https://github.com/microsoft/terminal',
 'https://github.com/alyssaxuu/mapus',
 'https://github.com/MoienTajik/AspNetCore-Developer-Roadmap',
 'https://github.com/Apress/Ray-Tracing-Gems-II',
 'https://github.com/chuzhixin/vue-admin-beautiful-pro',
 'https://github.com/microsoft/PowerToys',
 'https://github.com/ibraheemdev/modern-unix',
 'https://github.com/sysprog21/lkmpg',
 'https://github.com/actions/virtual-environments',
 'https://github.com/metersphere/metersphere',
 'https://github.com/JetBrains/compose-jb',
 'https://github.com/Security-Onion-Solutions/securityonion',
 'https://github.com/3b1b/manim',
 'https://github.com/dotnet-architecture/eShopOnContainers',
 'https://github.com/typescript-eslint/typescript-eslint',
 'https://github.com/commaai/openpilot']

In [8]:
len(url_respository)

25

In [7]:
# Scraping respository title
title_tag5 = driver.find_elements_by_xpath('//h1[@class="h3 lh-condensed"]')
for t in title_tag5:
    try:
        respository_title.append(t.text.replace('/',''))
    except NoSuchElementException:
        respository_title.append('--')
respository_title

['Azure  azure-sdk-for-net',
 'SheetJS  sheetjs',
 '0x727  ShuiZe_0x727',
 'OAI  OpenAPI-Specification',
 'microsoft  ML-For-Beginners',
 'apache  apisix',
 'geekxh  hello-algorithm',
 'GhostPack  Rubeus',
 'datafuselabs  datafuse',
 'microsoft  terminal',
 'alyssaxuu  mapus',
 'MoienTajik  AspNetCore-Developer-Roadmap',
 'Apress  Ray-Tracing-Gems-II',
 'chuzhixin  vue-admin-beautiful-pro',
 'microsoft  PowerToys',
 'ibraheemdev  modern-unix',
 'sysprog21  lkmpg',
 'actions  virtual-environments',
 'metersphere  metersphere',
 'JetBrains  compose-jb',
 'Security-Onion-Solutions  securityonion',
 '3b1b  manim',
 'dotnet-architecture  eShopOnContainers',
 'typescript-eslint  typescript-eslint',
 'commaai  openpilot']

In [8]:
len(respository_title)

25

In [9]:
# Scraping contributer count
count_tag5 = driver.find_elements_by_xpath('//a[@class="Link--muted d-inline-block mr-3"]')
data5 = []
for c in count_tag5:
    try:
        data5.append(c.text)
    except NoSuchElementException:
        data5.append('--')
time.sleep(5)        

for i5 in range (0, len(data5)):
    if i5%2:
        count_contributor.append(data5[i5])
    
count_contributor

['2,850',
 '6,915',
 '119',
 '7,648',
 '3,668',
 '1,150',
 '5,274',
 '347',
 '132',
 '6,816',
 '49',
 '1,163',
 '12',
 '2,253',
 '3,172',
 '297',
 '86',
 '1,369',
 '1,186',
 '292',
 '159',
 '4,178',
 '7,743',
 '1,719',
 '5,336']

In [10]:
len(count_contributor)

25

In [11]:
# Scraping respository description
for u in url_respository:
    driver.get(u)
    
    desc_tag5 = driver.find_elements_by_xpath('//*[@id="repo-content-pjax-container"]/div/div[2]/div[2]/div/div[1]/div')
    for d in desc_tag5:
        if d.text is None:
            description_respository.append('--')
        else:
            description_respository.append(d.text.replace('\n',''))
        
description_respository

['AboutThis repository is for active development of the Azure SDK for .NET. For consumers of the SDK we recommend visiting our public developer docs at https://docs.microsoft.com/en-us/dotnet/azure/ or our versioned developer docs at https://azure.github.io/azure-sdk-for-net.Topicsmicrosoft c-sharp azure swagger azure-sdk hacktoberfestResourcesReadmeLicenseMIT License',
 'About📗 SheetJS Community Edition -- Spreadsheet Data Toolkitsheetjs.com/Topicsreact nodejs javascript html ios json data angular grid csv database html5 vue xml excel table xlsx xls spreadsheet dbfResourcesReadmeLicenseApache-2.0 License',
 'About信息收集自动化工具ResourcesReadme',
 'AboutThe OpenAPI Specification Repositoryopenapis.orgTopicsrest openapi apis oas webapi openapi-specificationResourcesReadmeLicenseApache-2.0 License',
 'About12 weeks, 25 lessons, 50 quizzes, classic Machine Learning for allaka.ms/ml-beginnersTopicspython data-science machine-learning scikit-learn machine-learning-algorithms ml machinelearning machinelearning-python scikit-learn-pythonResourcesReadmeLicenseMIT License',
 'AboutThe Cloud-Native API Gatewayapisix.apache.org/Topicsapi docker nginx kubernetes iot devops microservices lua serverless api-management api-gateway luajit apigateway reverse-proxy cloud-native loadbalancing apisixResourcesReadmeLicenseApache-2.0 License',
 'About🌍 针对小白的算法训练 | 包括四部分：①.算法基础 ②.力扣图解 ③.大厂面经 ④.CS_汇总 | 附：1、千本开源电子书 2、百张技术思维导图（项目花了上百小时，希望可以点 star 支持，🌹感谢~）www.geekxh.comTopicsalgorithms leetcode leetcode-solutions interview-questions dynamic-programmingResourcesReadme',
 'AboutTrying to tame the three-headed dog.TopicskerberosResourcesReadmeLicenseView license',
 'AboutA Modern Real-Time Data Processing & Analytics DBMS with Cloud-Native Architecture, built to make the Data Cloud easydatafuse.rsTopicsrust streaming sql database clickhouse olap data-cloud query-processingResourcesReadmeLicenseApache-2.0 License',
 'AboutThe new Windows Terminal and the original Windows console host, all in the same place!Topicsconsole terminal command-line wsl cmd windows-console windows-terminalResourcesReadmeLicenseMIT License',
 'AboutA map tool with real-time collaboration 🗺️Topicsjavascript map drawing firebase real-time annotation maps google-maps openstreetmap leaflet collaboration planning trip leafletjsResourcesReadmeLicenseMIT License',
 'AboutRoadmap to becoming an ASP.NET Core developer in 2021Topicsroadmap dotnet aspnetcore dotnet-core aspnet-core asp-net-coreResourcesReadme',
 'AboutSource Code for "Ray Tracing Gems II: Next Generation Real-Time Rendering with DXR, Vulkan, and OptiX" by Adam Marrs, Peter Shirley, and Ingo Waldwww.apress.com/book/9781484271841ResourcesReadmeLicenseMIT License',
 'About团结一心，共抗疫情，烟台加油！！！🚀🚀🚀vue3,vue3.0,vue,vue3.x,vue.js,vue后台管理,admin,vue-admin,vue-element-admin,ant-design，vue-admin-beautiful-pro,vab admin pro,vab admin plus主线版本基于element-plus、element-ui、ant-design-vue三者并行开发维护，同时支持电脑，手机，平板，切换分支查看不同的vue版本，element-plus版本已发布(vue3,vue3.0,vue,vue3.x,vue.js)程序无国界，但程序员有国界，中国国家尊严不容挑衅，如果您在特殊时期继续购买HM、耐克、阿迪达斯等品牌那么您将无权继续使用Vabchu1204505056.gitee.io/admin-pro?hmsr=github&hmpl=&hmcu=&hmkw=&hmci=Topicsmock vuejs adminlte admin spring-boot vue element vue-cli admin-dashboard axios vue-template admin-template ant-design element-ui vue-admin vue-element-admin vue3 ant-design-vue vue3-composition-api element-plusResourcesReadmeLicenseMIT License',
 'AboutWindows system utilities to maximize productivityTopicswindows color-picker desktop keyboard-manager powertoys fancyzones microsoft-powertoys powerrenameResourcesReadmeLicenseMIT License',
 'AboutA collection of modern/faster/saner alternatives to common unix commands.Topicsshell cli lists unix terminal tools command-lineResourcesReadme',
 'AboutThe Linux Kernel Module Programming Guide (updated for 5.x kernels)sysprog21.github.io/lkmpg/Topicslinux kernel linux-kernel linux-kernel-module linux-kernel-driver lkmResourcesReadmeLicenseOSL-3.0 License',
 'AboutGitHub Actions virtual environmentsResourcesReadmeLicenseMIT License',
 'AboutMeterSphere 是一站式开源持续测试平台，涵盖测试跟踪、接口测试、性能测试、团队协作等功能，全面兼容 JMeter、Postman、Swagger 等开源、主流标准。metersphere.io/Topicstesting swagger jmeter test-automation postman continuous-testing testcase api-testing performance-testing testlink testlink-alternative metersphereResourcesReadmeLicenseGPL-2.0 License',
 'AboutJetpack Compose for Desktop and Web, a modern UI framework for Kotlin that makes building performant and beautiful user interfaces easy and enjoyable.jetbrains.com/lp/compose/Topicsjavascript android kotlin gui reactive ui swing desktop declarative-ui multiplatform compose awtResourcesReadmeLicenseApache-2.0 License',
 'AboutSecurity Onion 2 - Linux distro for threat hunting, enterprise security monitoring, and log managementResourcesReadme',
 'AboutAnimation engine for explanatory math videosTopicspython animation explanatory-math-videos 3b1b-videosResourcesReadmeLicenseMIT License',
 'AboutCross-platform .NET sample microservices and container based application that runs on Linux Windows and macOS. Powered by .NET 5, Docker Containers and Azure Kubernetes Services. Supports Visual Studio, VS for Mac and CLI based environments with Docker CLI, dotnet CLI, VS Code or any other code editor.dot.net/architectureTopicsdocker microservices spa xamarin ddd netcore ddd-patterns windowscontainersResourcesReadmeLicenseMIT License',
 'About✨ Monorepo for all the tooling which enables ESLint to support TypeScripttypescript-eslint.ioTopicsplugin typescript eslint tslint eslint-plugin hacktoberfest eslintpluginResourcesReadmeLicenseView license',
 'Aboutopenpilot is an open source driver assistance system. openpilot performs the functions of Automated Lane Centering and Adaptive Cruise Control for over 100 supported car makes and models.comma.ai/ResourcesReadmeLicenseMIT License']

In [12]:
len(description_respository)

25

In [52]:
# Scraping language used

for u in url_respository:
    driver.get(u)
    lan_tag5 = driver.find_elements_by_xpath('//*[@id="repo-content-pjax-container"]/div/div[2]/div[2]/div/div/div/ul/li[1]/a/span[1]')
    if lan_tag5:
        for l in lan_tag5:
            used_language.append(l.text.replace('\n',''))
    else:
        used_language.append('No languages used')
        

used_language

['C#',
 'JavaScript',
 'Python',
 'JavaScript',
 'Jupyter Notebook',
 'Lua',
 'Java',
 'C#',
 'Rust',
 'C++',
 'JavaScript',
 'No languages used',
 'C++',
 'Vue',
 'C#',
 'No languages used',
 'TeX',
 'PowerShell',
 'Java',
 'Kotlin',
 'Shell',
 'Python',
 'C#',
 'TypeScript',
 'C++']

In [53]:
len(used_language)

25

In [55]:
github = pd.DataFrame({'Respository Title':respository_title, 'Respository Description':description_respository,
                       'Contributor Count':count_contributor, 'Language Used':used_language})

github

,Respository Title,Respository Description,Contributor Count,Language Used
0,Azure azure-sdk-for-net,AboutThis repository is for active development...,"2,850",C#
1,SheetJS sheetjs,About📗 SheetJS Community Edition -- Spreadshee...,"6,915",JavaScript
2,0x727 ShuiZe_0x727,About信息收集自动化工具ResourcesReadme,119,Python
3,OAI OpenAPI-Specification,AboutThe OpenAPI Specification Repositoryopena...,"7,648",JavaScript
4,microsoft ML-For-Beginners,"About12 weeks, 25 lessons, 50 quizzes, classic...","3,668",Jupyter Notebook
5,apache apisix,AboutThe Cloud-Native API Gatewayapisix.apache...,"1,150",Lua
6,geekxh hello-algorithm,About🌍 针对小白的算法训练 | 包括四部分：①.算法基础 ②.力扣图解 ③.大厂面经 ...,"5,274",Java
7,GhostPack Rubeus,AboutTrying to tame the three-headed dog.Topic...,347,C#
8,datafuselabs datafuse,AboutA Modern Real-Time Data Processing & Anal...,132,Rust
9,microsoft terminal,AboutThe new Windows Terminal and the original...,"6,816",C++
10,alyssaxuu mapus,AboutA map tool with real-time collaboration 🗺...,49,JavaScript
11,MoienTajik AspNetCore-Developer-Roadmap,AboutRoadmap to becoming an ASP.NET Core devel...,"1,163",No languages used
12,Apress Ray-Tracing-Gems-II,"AboutSource Code for ""Ray Tracing Gems II: Nex...",12,C++
13,chuzhixin vue-admin-beautiful-pro,"About团结一心，共抗疫情，烟台加油！！！🚀🚀🚀vue3,vue3.0,vue,vue3....","2,253",Vue
14,microsoft PowerToys,AboutWindows system utilities to maximize prod...,"3,172",C#
15,ibraheemdev modern-unix,AboutA collection of modern/faster/saner alter...,297,No languages used
16,sysprog21 lkmpg,AboutThe Linux Kernel Module Programming Guide...,86,TeX
17,actions virtual-environments,AboutGitHub Actions virtual environmentsResour...,"1,369",PowerShell
18,metersphere metersphere,AboutMeterSphere 是一站式开源持续测试平台，涵盖测试跟踪、接口测试、性能测试...,"1,186",Java
19,JetBrains compose-jb,"AboutJetpack Compose for Desktop and Web, a mo...",292,Kotlin
20,Security-Onion-Solutions securityonion,AboutSecurity Onion 2 - Linux distro for threa...,159,Shell
21,3b1b manim,AboutAnimation engine for explanatory math vid...,"4,178",Python
22,dotnet-architecture eShopOnContainers,AboutCross-platform .NET sample microservices ...,"7,743",C#
23,typescript-eslint typescript-eslint,About✨ Monorepo for all the tooling which enab...,"1,719",TypeScript
24,commaai openpilot,Aboutopenpilot is an open source driver assist...,"5,336",C++

-------------------------------------------------------------------------------------------------------------------------------

#### Q. No. 6:- 

- Scrape the details of top 100 songs on billboard.com.
- Url = https://www.billboard.com/
- You have to find the following details:
    - Song name
    - Artist name
    - Last week rank
    - Peak rank
    - Weeks on board

#### Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [6]:
# Loading the web page

url6 = 'https://www.billboard.com/'
driver.get(url6)

In [7]:
# visiting the hot 100 page

charts_tag6 = driver.find_element_by_xpath('//*[@id="root"]/div[2]/div[2]/header/div/ul/li[1]')
charts_tag6.click()

In [8]:
hot_tag6 = driver.find_element_by_xpath('//*[@id="main"]/div[2]/div/div[1]/a/div[2]/div[2]')
hot_tag6.click()

In [9]:
# Creating empty list

name_song = []
name_artist = []
last_week_rank = []
peak_rank = []
weeks_board = []

In [10]:
# Scraping the song name
nme_sng = driver.find_elements_by_xpath('//span[@class="chart-element__information__song text--truncate color--primary"]')
for n in nme_sng:
    try:
        name_song.append(n.text)
    except NoSuchElementException:
        name_song.append('--')
        
name_song

['Butter',
 'Good 4 U',
 'Levitating',
 'Stay',
 'Kiss Me More',
 'Bad Habits',
 'Permission To Dance',
 'Montero (Call Me By Your Name)',
 'Deja Vu',
 'Save Your Tears',
 'Peaches',
 'Leave The Door Open',
 'Rapstar',
 'Wild Side',
 'Fancy Like',
 'Heartbreak Anniversary',
 'Blinding Lights',
 'Astronaut In The Ocean',
 'You Right',
 'Without You',
 'Forever After All',
 'Every Chance I Get',
 'Motley Crew',
 'Leave Before You Love Me',
 'Thot Shit',
 'Lil Bit',
 'Single Saturday Night',
 'Famous Friends',
 'Beautiful Mistakes',
 'Whole Lotta Money',
 "Ain't Shit",
 'Heat Waves',
 'Late At Night',
 'Glad You Exist',
 "Beggin'",
 'Blame It On You',
 "Drinkin' Beer. Talkin' God. Amen.",
 'Telepatia',
 'Traitor',
 'Best Friend',
 'Mood',
 "My Ex's Best Friend",
 'Drivers License',
 'Yonaguni',
 'Todo de Ti',
 'Need To Know',
 'Wants And Needs',
 'Wockesha',
 'Tell The Vision',
 'Holy Smokes',
 'Things A Man Oughta Know',
 'pov',
 'Settling Down',
 'Bout A Million',
 'One Too Many',
 'Ball If I Want To',
 'Arcade',
 'Chasing After You',
 "Drunk (And I Don't Wanna Go Home)",
 'You',
 'Waves',
 'Way Less Sad',
 'Gone',
 'Woo Baby',
 "We Didn't Have Much",
 'Country Again',
 'Essence',
 'Favorite Crime',
 'my.life',
 'Memory',
 'Mr. Jones',
 'Straightenin',
 'AM',
 'Ski',
 'NDA',
 'Happier',
 'Tombstone',
 'A-O-K',
 'Red Light Green Light',
 'More Time',
 'Hats Off',
 'Manslaughter',
 'Minimum Wage',
 'Come Through',
 'Fiel',
 'Demeanor',
 '2055',
 'Brutal',
 'Love Again',
 'I Was On A Boat That Day',
 'WUSYANAME',
 'transparentsoul',
 'Am I The Only One',
 'Twerkulator',
 'My Boy',
 'Build A Bitch',
 '30',
 'You Should Probably Leave',
 'Jealousy, Jealousy',
 'Cold Beer Calling My Name']

In [11]:
len(name_song)

100

In [12]:
# Scraping artist name
art_nme = driver.find_elements_by_xpath('//span[@class="chart-element__information__artist text--truncate color--secondary"]')
for a in art_nme:
    try:
        name_artist.append(a.text)
    except NoSuchElementException:
        name_artist.append('--')
        
name_artist

['BTS',
 'Olivia Rodrigo',
 'Dua Lipa Featuring DaBaby',
 'The Kid LAROI & Justin Bieber',
 'Doja Cat Featuring SZA',
 'Ed Sheeran',
 'BTS',
 'Lil Nas X',
 'Olivia Rodrigo',
 'The Weeknd & Ariana Grande',
 'Justin Bieber Featuring Daniel Caesar & Giveon',
 'Silk Sonic (Bruno Mars & Anderson .Paak)',
 'Polo G',
 'Normani Featuring Cardi B',
 'Walker Hayes',
 'Giveon',
 'The Weeknd',
 'Masked Wolf',
 'Doja Cat & The Weeknd',
 'The Kid LAROI',
 'Luke Combs',
 'DJ Khaled Featuring Lil Baby & Lil Durk',
 'Post Malone',
 'Marshmello X Jonas Brothers',
 'Megan Thee Stallion',
 'Nelly & Florida Georgia Line',
 'Cole Swindell',
 'Chris Young + Kane Brown',
 'Maroon 5 Featuring Megan Thee Stallion',
 'BIA Featuring Nicki Minaj',
 'Doja Cat',
 'Glass Animals',
 'Roddy Ricch',
 'Dan + Shay',
 'Maneskin',
 'Jason Aldean',
 'Chase Rice Featuring Florida Georgia Line',
 'Kali Uchis',
 'Olivia Rodrigo',
 'Saweetie Featuring Doja Cat',
 '24kGoldn Featuring iann dior',
 'Machine Gun Kelly X blackbear',
 'Olivia Rodrigo',
 'Bad Bunny',
 'Rauw Alejandro',
 'Doja Cat',
 'Drake Featuring Lil Baby',
 'Moneybagg Yo',
 'Pop Smoke Featuring Kanye West & Pusha T',
 'Trippie Redd Featuring Lil Uzi Vert',
 'Lainey Wilson',
 'Ariana Grande',
 'Miranda Lambert',
 'Pop Smoke Featuring 21 Savage & 42 Dugg',
 'Keith Urban Duet With P!nk',
 'DaBaby',
 'Duncan Laurence',
 'Ryan Hurd With Maren Morris',
 'Elle King & Miranda Lambert',
 'Regard x Troye Sivan x Tate McRae',
 'Luke Bryan',
 'AJR',
 'Dierks Bentley',
 'Pop Smoke Featuring Chris Brown',
 'Justin Moore',
 'Thomas Rhett',
 'Wizkid Featuring Tems',
 'Olivia Rodrigo',
 'J. Cole, 21 Savage & Morray',
 'Kane Brown X blackbear',
 'Pop Smoke Featuring Future',
 'Migos',
 'Nio Garcia X J Balvin X Bad Bunny',
 'Young Thug & Gunna',
 'Billie Eilish',
 'Olivia Rodrigo',
 'Rod Wave',
 'Tai Verdes',
 'DaBaby',
 'Pop Smoke',
 'Lil Baby, Lil Durk & Travis Scott',
 'Pop Smoke Featuring Rick Ross & The-Dream',
 'Blake Shelton',
 'H.E.R. Featuring Chris Brown',
 'Los Legendarios, Wisin & Jhay Cortez',
 'Pop Smoke Featuring Dua Lipa',
 'Sleepy Hallow',
 'Olivia Rodrigo',
 'Dua Lipa',
 'Old Dominion',
 'Tyler, The Creator Featuring YoungBoy Never Broke Again & Ty Dolla $ign',
 'Willow Featuring Travis Barker',
 'Aaron Lewis',
 'City Girls',
 'Elvie Shane',
 'Bella Poarch',
 'Pop Smoke Featuring Bizzy Banks',
 'Chris Stapleton',
 'Olivia Rodrigo',
 'Jameson Rodgers Featuring Luke Combs']

In [13]:
len(name_artist)

100

In [18]:
# Scraping the last week rank of the song
last_rnk = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--last"]')
for l in last_rnk:
    try:
        last_week_rank.append(l.text)
    except NoSuchElementException:
        last_week_rank.append('--')
        
last_week_rank

['7',
 '2',
 '4',
 '3',
 '5',
 '6',
 '1',
 '8',
 '10',
 '9',
 '11',
 '12',
 '14',
 '-',
 '21',
 '18',
 '17',
 '15',
 '19',
 '20',
 '22',
 '23',
 '13',
 '28',
 '25',
 '29',
 '27',
 '24',
 '26',
 '16',
 '34',
 '35',
 '33',
 '31',
 '41',
 '30',
 '40',
 '36',
 '45',
 '32',
 '43',
 '44',
 '42',
 '38',
 '47',
 '63',
 '37',
 '46',
 '-',
 '-',
 '59',
 '48',
 '54',
 '-',
 '52',
 '51',
 '58',
 '56',
 '53',
 '61',
 '73',
 '60',
 '55',
 '-',
 '70',
 '71',
 '72',
 '57',
 '65',
 '50',
 '-',
 '62',
 '66',
 '64',
 '39',
 '68',
 '81',
 '83',
 '67',
 '-',
 '75',
 '-',
 '82',
 '79',
 '77',
 '-',
 '-',
 '76',
 '-',
 '85',
 '69',
 '93',
 '-',
 '80',
 '90',
 '84',
 '-',
 '91',
 '87',
 '95']

In [19]:
len(last_week_rank)

100

In [20]:
# Scraping peak rank
pek_rnk = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--peak"]')
for p in pek_rnk:
    try:
        peak_rank.append(p.text)
    except NoSuchElementException:
        peak_rank.append('--')
        
peak_rank

['1',
 '1',
 '2',
 '3',
 '3',
 '5',
 '1',
 '1',
 '3',
 '1',
 '1',
 '1',
 '1',
 '14',
 '15',
 '16',
 '1',
 '6',
 '11',
 '8',
 '2',
 '20',
 '13',
 '24',
 '16',
 '23',
 '26',
 '21',
 '13',
 '16',
 '24',
 '19',
 '20',
 '31',
 '35',
 '30',
 '37',
 '25',
 '9',
 '14',
 '1',
 '20',
 '1',
 '10',
 '32',
 '38',
 '2',
 '33',
 '49',
 '50',
 '51',
 '27',
 '41',
 '54',
 '52',
 '39',
 '57',
 '56',
 '53',
 '60',
 '61',
 '54',
 '26',
 '64',
 '65',
 '66',
 '67',
 '16',
 '2',
 '50',
 '71',
 '23',
 '41',
 '18',
 '39',
 '15',
 '11',
 '78',
 '50',
 '80',
 '16',
 '82',
 '67',
 '64',
 '62',
 '86',
 '87',
 '12',
 '89',
 '85',
 '14',
 '76',
 '14',
 '51',
 '88',
 '56',
 '97',
 '90',
 '24',
 '95']

In [21]:
len(peak_rank)

100

In [22]:
# Scraping week on board
board_tag = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--week"]')
for b in board_tag:
    try:
        weeks_board.append(b.text)
    except NoSuchElementException:
        weeks_board.append('--')
        
weeks_board

['9',
 '10',
 '42',
 '2',
 '15',
 '4',
 '2',
 '17',
 '16',
 '32',
 '18',
 '20',
 '15',
 '1',
 '5',
 '23',
 '85',
 '23',
 '4',
 '33',
 '39',
 '12',
 '2',
 '9',
 '6',
 '18',
 '12',
 '17',
 '20',
 '2',
 '4',
 '27',
 '7',
 '24',
 '4',
 '13',
 '8',
 '22',
 '9',
 '28',
 '50',
 '49',
 '28',
 '7',
 '8',
 '6',
 '20',
 '13',
 '1',
 '1',
 '10',
 '20',
 '19',
 '1',
 '32',
 '5',
 '15',
 '12',
 '13',
 '6',
 '5',
 '13',
 '19',
 '1',
 '5',
 '12',
 '3',
 '9',
 '10',
 '2',
 '1',
 '10',
 '4',
 '14',
 '2',
 '9',
 '17',
 '3',
 '4',
 '1',
 '7',
 '1',
 '11',
 '7',
 '6',
 '1',
 '1',
 '9',
 '1',
 '3',
 '4',
 '6',
 '2',
 '7',
 '4',
 '10',
 '1',
 '3',
 '9',
 '3']

In [23]:
len(weeks_board)

100

In [24]:
# Creating the dataframe 

songs = pd.DataFrame({'Song Name':name_song, 'Artist Name':name_artist, 'Last Week Rank':last_week_rank,
                      'Peak Rank':peak_rank, 'Weeks on Board':weeks_board})

songs

,Song Name,Artist Name,Last Week Rank,Peak Rank,Weeks on Board
0,Butter,BTS,7,1,9
1,Good 4 U,Olivia Rodrigo,2,1,10
2,Levitating,Dua Lipa Featuring DaBaby,4,2,42
3,Stay,The Kid LAROI & Justin Bieber,3,3,2
4,Kiss Me More,Doja Cat Featuring SZA,5,3,15
...,...,...,...,...,...
95,Build A Bitch,Bella Poarch,84,56,10
96,30,Pop Smoke Featuring Bizzy Banks,-,97,1
97,You Should Probably Leave,Chris Stapleton,91,90,3
98,"Jealousy, Jealousy",Olivia Rodrigo,87,24,9
99,Cold Beer Calling My Name,Jameson Rodgers Featuring Luke Combs,95,95,3

------------------------------------------------------------------------------------------------------------------------------

#### Q. No. 7:-

- Scrape the details of Data science recruiters from naukri.com.
- Url = https://www.naukri.com/
- You have to find the following details:
    - Name
    - Designation
    - Company
    - Skills they hire for
    - Location
#### Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [3]:
# Loading the web driver

driver = webdriver.Chrome("chromedriver.exe")

In [3]:
# Loading the web page

url7 = 'https://www.naukri.com/'
driver.get(url7)

In [4]:
# Clicking on 'Recruiters'
recruiter_tag7 = driver.find_element_by_xpath('//a[@title="Search Recruiters"]')
driver.get(recruiter_tag7.get_attribute('href'))

In [5]:
# typing 'Data Science' in the search bar
src_tag7 = driver.find_element_by_xpath('//input[@class="sugInp"]')
src_tag7.send_keys('Data Science')
time.sleep(2)

# Clicking on the search button
src_btn = driver.find_element_by_xpath('//button[@class="fl qsbSrch blueBtn"]')
src_btn.click()

In [6]:
# Creating the empty lists

name_recruiter = []
designation_recruiter = []
company_recruiter = []
skills_recruiters = []
location_recruiter = []

In [7]:
# Scraping name of the recruiter

nme_tag7 = driver.find_elements_by_xpath('//span[@class="fl ellipsis"]')
for n in nme_tag7:
    try:
        name_recruiter.append(n.text)
    except NoSuchElementException:
        name_recruiter.append('--')
        
name_recruiter

['Aakash Harit',
 'shravan Kumar Gaddam',
 'MARSIAN Technologies LLP',
 'Anik Agrawal',
 'subhas patel',
 'Abhishek - Only Analytics Hiring - India and',
 'Institute for Financial Management and Resear',
 'Balu Ramesh',
 'Asif Lucknowi',
 'InstaFinancials',
 'Kalpana Dumpala',
 'Mubarak',
 'Kushal Rastogi',
 'Ruchi Dhote',
 'Mahesh Babu Channa',
 'Kapil Devang',
 'Manisha Yadav',
 'Riya Rajesh',
 'Rashmi Bhattacharjee',
 'Faizan Kareem',
 'Rithika dadwal',
 'Sandhya Khandagale',
 'Shaun Rao',
 'Azahar Shaikh',
 'Manas',
 'kumar',
 'Sunil Vedula',
 'Rajat Kumar',
 'Priya Khare',
 'Dhruv Dev Dubey',
 'Jayanth N',
 'Radha Manivasagam',
 'Prateek Kumar',
 'Amit Sharma',
 'Kanan',
 'Shashikant Chaudhary',
 'Brad',
 'Rutuja Pawar',
 'Madhusudhan Sridhar',
 'Ankit Sinha',
 'Gaurav Chouhan',
 'Rashi Kacker',
 'Ashwini',
 'Balaji Kolli',
 'Rajani Nagaraj',
 'ROHIT Kumar',
 'Amir Chowdhury',
 'Shailja Mishra',
 'Sunny Sharma',
 'Sagar Lama']

In [8]:
len(name_recruiter)

50

In [9]:
# Scraping Designation
desig_tag7 = driver.find_elements_by_xpath('//span[@class="ellipsis clr"]')
for d in desig_tag7:
    try:
        designation_recruiter.append(d.text)
    except NoSuchElementException:
        designation_recruiter.append('--')
        
designation_recruiter

['HR Manager',
 'Company Recruiter',
 'Company HR',
 'Company Recruiter',
 'Founder CEO',
 'Recruitment Lead Consultant',
 'Programme Manager',
 'HR Administrator',
 'Director',
 'Human Resource',
 'Executive Hiring',
 'Company HR',
 'Company HR',
 'Senior Executive Talent Acquisition',
 'HR Team Lead',
 'HR Manager',
 'HR Executive',
 'Manager Talent Acquisition',
 'HR Head',
 'HR MANAGER',
 'HR Recruiter',
 'HR Recruiter',
 'Manager Human Resources',
 'Company Recruiter',
 'Lead Talent acquisition',
 'Proprietor',
 'CEO',
 'Founder CEO',
 'Senior Manager',
 'Company Recruitment Head',
 'Project Manager',
 'HR Executive',
 'Head',
 'Consultant',
 'senior technology instructor',
 'HR Recruiter/HR Excutive',
 'Manager, Technical Recruiting',
 'Technical Recruiter',
 'Erp Implementer',
 'Head Analytics',
 'Chief Technical Officer',
 'Sr Product Manager',
 'Director Global Delivery',
 'Co Founder',
 'HR Manager',
 'Architect',
 'Managing Partner',
 'HR Manager',
 'Managing Director - HR',
 'Company HR Manager']

In [10]:
len(designation_recruiter)

50

In [11]:
# Scraping Company
cmp_tag7 = driver.find_elements_by_xpath('//a[@class="ellipsis"]')
data7 = []
for c in cmp_tag7:
    try:
        data7.append(c.text)
    except NoSuchElementException:
        data7.append('--')
        
time.sleep(5)
for i in range(0,len(data7)):
    if i%2:
        company_recruiter.append(data7[i])
    
company_recruiter

['Data Science Network',
 'Shore Infotech India Pvt. Ltd',
 'MARSIAN Technologies LLP',
 'Enerlytics Software Solutions Pvt Ltd',
 'LibraryXProject',
 'Apidel Technologies Division of Transpower',
 'IFMR',
 'Techvantage Systems Pvt Ltd',
 'Weupskill- Live Wire India',
 'CBL Data Science Private Limited',
 'Innominds Software',
 'MoneyTap',
 'QuantMagnum Technologies Pvt. Ltd.',
 'Bristlecone India Ltd',
 'SocialPrachar.com',
 'BISP Solutions',
 'Easi Tax',
 'Novelworx Digital Solutions',
 'AXESTRACK SOFTWARE SOLUTIONS PRIVATE...',
 'FirstTech Consaltants Pvt.Ltd',
 'Affine Analytics',
 'Compumatrice Multimedia Pvt Ltd',
 'Exela Technologies',
 'NEAL ANALYTICS SERVICES PVT LTD',
 'Autumn Leaf Consulting Services Private...',
 'trainin',
 'Nanoprecise Sci Corp',
 'R.S Consultancy &amp; Services',
 'Independent Consultant',
 'Confidential',
 'Dollarbird Information Services Pvt, Ltd',
 'Techcovery',
 'Trisect',
 'ASCO consulting',
 'NY INST',
 '3D India Staffing Research &amp; Consulting...',
 'O.C. Tanner',
 'Demand Matrix',
 'MADHUSUDHAN SRIDHAR',
 'Suntech Global',
 'Strategic Consulting Lab',
 'Impel Labs Pvt. Ltd.',
 'MRP Advisers',
 'Saras Solutions India Pvt Ltd',
 'WildJasmine',
 'LNT Private Limited',
 'Granular.ai',
 'Certybox Pvt.Ltd.',
 'Western Service Providers',
 'AdView']

In [12]:
len(company_recruiter)

50

In [13]:
# Scraping the skills recruiter hire for

skill_tag7 = driver.find_elements_by_xpath('//div[@class="hireSec highlightable"]')
for s in skill_tag7:
    try:
        skills_recruiters.append(s.text)
    except NoSuchElementException:
        skills_recruiters.append('--')
        
skills_recruiters

['Classic ASP Developer, Internet Marketing Professional, Data Science SME, Content Writers, SEO Professional, Revenue Professional',
 '.Net, Java, Data Science, Linux Administration, Sql Server Development, Winforms, Wcf Services, Wpf, Telecom Engineering, Technical Management, Software',
 'Data Science, Artificial Intelligence, Machine Learning, Business Analytics',
 'Mean Stack, javascript, angularjs, mongodb, Web Services, rest, express, Node.js, Big Data, iot, Data Science, Cloud Computing, saas, Aws',
 'Hadoop, Spark, Digital Strategy, Data Architecture, Command Center, Cdp, Dmp, Kafka, Data Science, Data Analysis, Big Data Analytics, Real Time Analysis, SQL',
 'Analytics, Business Intelligence, Business Analytics, Predictive Modeling, Predictive Analytics, Data Science, Data Analysis, Data Analytics, Big Data, Big',
 'Data Science',
 'Machine Learning, algorithms, Go Getter, Computer Science, spark, Big Data, hdfs, sql, cassandra, hadoop, python, scala, java, Data Science, Front End',
 'Technical Training, Software Development, Presentation Skills, B.tech, M.tech, B.e., mca, msc, Computer Science, freshers, jobs in indore, Data Science, itil',
 'Software Development, It Sales, Account Management, Data Analysis, Customer Service, Sr, Software Engineering, Mvc, Ajax, Asp.net, Html, C#, Javascript',
 'Qa, Ui/ux, Java Developer, Java Architect, C++/qt, Php, Lamp, Api, J2ee, Java, Soa, Esb, Middleware, Bigdata Achitect, Hadoop Architect, Deep',
 'Business Intelligence, Data Warehousing, Data Science, Business Analytics, Customer Support, Business Reporting, Bi',
 'Office Administration, Hr Administration, telecalling, client relationship management, Client Acquisition, Sales, Reception, HR, Recruitment, Onboarding, Human',
 'Qlikview, Qlik Sense, Microsoft Azure, Power Bi, Data Science, Machine Learning',
 'Social Media, digital media maketing, seo, smm, smo, sem, Content Wirting, social media marketing, social media manager, digital media marketing manager',
 'Big Data, Hadoop, Data Analytics, Data Science',
 'Telecalling, Client Interaction, Marketing, Research, Web Development, Social Media Marketing, Data Entry Operation, Excel, Ms Office, Invoicing',
 'Data Science',
 'Corporate Sales, Software Development, Software Sales, Marketing, Creative Designing, Corporate Planning, Senior Management, Crm, Client Relationship',
 'Data Analytics, Data Science, Machine Learning, Deep Learning, Nlp, Data Mining, Python, R, Database Administration, Text Mining',
 'Data Science, Machine Learning, Python, R, Deep Learning, Big Data, Hadoop',
 'Big Data, Data Science, Artificial Intelligence, Hadoop, Ui Development, Php, Freelancing, .Net, Software Testing, Sap, Leadership Hiring',
 'Java, Net, Angularjs, Hr, Infrastructure, Management, Project Management, Business Analysis, Data Science, Information Technology, Technology',
 'Data Science, Artificial Intelligence, Machine Learning, Data Analytics',
 'Software Architecture, Vp Engineering, Product Management, analytics, Data Science, Node.js, Principal Engineer, Big Data, python, angularjs, React.js',
 'Data Science, Hadoop, Rpas, Devops, Python, Aws, Teaching, Big Data',
 'Signal Processing, Machine Learning, Neural Networks, Data Science, Predictive Analytics, Time Series Analysis, Data Visualization, Technical Leadership, Data',
 'Web Technologies, Project Management, Software Architecture, Data Science, Object Oriented Programming, Computer Science, Electrical Engineering, Architecture',
 'Data Science, Artificial Intelligence, analytics, Business Intelligence, python, tableau, Power Bi, qlikview, sql, Data Warehousing, Data Visualization',
 'Server Administartion, Verilog, Vhdl, Digital Marketing, Market Research, Property Research, Legal, It And Non It Recruitment, Logistics, Supply Chain, Bfsi',
 'Data Analytics, Managed Services, Team Leading, python, Machine Learning, Google Analytics, Dmp, Aws, Campaign Analytics, Digital Campaigns, Audience',
 'Python, Artificial Intelligence, Machine Learning, Data Science',
 'Java, Python, Angularjs, Software Testing, Machine Learning, Data Science, Javascript, Django, React.js, Node.js, Augmented Reality, Virtual Reality, Advanced',
 'Machine Learning, Artificial Intelligence, Data Science, Software Engineering, Software Development, Graduate Engineer Trainee, Fresher, Data Analytics, Java',
 'C, C++, Artificial Intelligence, Python, Php, Web Development, Matlab, Data Science, Augmented Reality, C C++',
 'Relationship Management, Retail Sales, Private Banking, Mutual Funds, NISM, Equity, Finance, Financial Products, Financial Services, Verbal, Written',
 'Data Science, Software Engineering',
 'Data Science, Big Data Analytics, Digital Marketing, Content Writing, Ui Development, Database Development, Qa Automation, Python, Project Management',
 'Data Science, Recruitment, Salary',
 'B.Tech, Tableau, Statistics, R, Analytics, Time Series, Data Science, Business Solutions, SQL, Technical Skills, SSAS, SQL Server, Analysis Services, Qlikview',
 'Software Development, Business Intelligence, Big Data Analytics, Database Administration, Data Science, Microsoft Azure, Spark, Cassandra, Object Oriented',
 'Data Science, Node.js, Angularjs',
 'Data Science, Media Marketing, Resource Planning, Managed Services, Display Advertising, Machine Learning, Python, Etl, Sql',
 'Data Analysis, Learning, Data Science, Computer Science, Communication Skills',
 'Java, Hadoop, R, Machine Learning, Spark, Flume, Hdfs, Data Mining, Sas, Big, Data Science, Cloudera, Impala, Bigdata',
 'Software Development, Core Java, Unit Testing, Customer Experience, Problem Solving, Communication Skills, Mysql, Data Science, Sales Management, Analytics',
 'Machine Learning, Data Science, Product Management, New Product, Data Analysis, Computer Vision, Deep Learning, Python, Remote Sensing',
 'consulting, Education Counseling, Educational Sales, Institutional Sales, pmp, Data Science, Business Development, Revenue Generation, Sales Achievement, new',
 'Software Professionals, Engineering, Technical Management, Financial Management, Human Resource Management, Banking, Google Adwords, Business Analysis, It',
 'Full Stack Developers, Product Manager, Data Science Engineer, Publishers Sales Manager']

In [14]:
len (skills_recruiters)

50

In [17]:
# Scraping the URLs
url_7 = []
url_tag7 = driver.find_elements_by_xpath('//a[@class="ellipsis"]')
for u in url_tag7:
    url_7.append(u.get_attribute('href'))
time.sleep(2)

# Scraping the location
for u2 in url_7:
    driver.get(u2)
    
    loc_tag7 = driver.find_elements_by_css_selector('body > div.wrap > div.wrpSp.oh > div.frame.oh > div.rFrame.fl.infoWrapper > div:nth-child(5) > a')
    for l in loc_tag7:
        try:
            location_recruiter.append(l.text)
        except NoSuchElementException:
            location_recruiter.append('--')
                
location_recruiter

['Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Ahmedabad',
 'UK - (london)',
 'Vadodara / Baroda',
 'Chennai',
 'Trivandrum',
 'Indore',
 'Bengaluru / Bangalore',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Pune',
 'Hyderabad / Secunderabad',
 'Bhopal',
 'Navi Mumbai',
 'Cochin',
 'Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Others',
 'Delhi',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Mysoru / Mysore',
 'Bengaluru / Bangalore',
 'Noida',
 'New Delhi',
 'Chennai',
 'Aligarh',
 'Salt Lake City',
 'Pune',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Indore',
 'Bengaluru / Bangalore',
 'MYSORE',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 '',
 'Noida',
 'Mumbai',
 'Bengaluru / Bangalore']

In [18]:
len(location_recruiter)

50

In [19]:
# Creating dataframe:

recruiters = pd.DataFrame({'Name of Recruiter':name_recruiter, 'Designation':designation_recruiter, 
                          'Company Name':company_recruiter, 'Skills they hire for':skills_recruiters, 'Location':location_recruiter})

recruiters

,Name of Recruiter,Designation,Company Name,Skills they hire for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
11,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
13,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
15,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
16,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
17,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
18,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
19,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
20,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
21,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
22,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
23,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
24,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
25,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
26,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Others
27,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Delhi
28,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
29,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
30,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
31,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",Bengaluru / Bangalore
32,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac...",Noida
33,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
34,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
35,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Aligarh
36,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
37,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Pune
38,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
39,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
40,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Indore
41,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
42,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
43,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
44,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
45,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai
46,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",
47,Shailja Mishra,HR Manager,Certybox Pvt.Ltd.,"consulting, Education Counseling, Educational ...",Noida
48,Sunny Sharma,Managing Director - HR,Western Service Providers,"Software Professionals, Engineering, Technical...",Mumbai
49,Sagar Lama,Company HR Manager,AdView,"Full Stack Developers, Product Manager, Data S...",Bengaluru / Bangalore

-------------------------------------------------------------------------------------------------------------------------------

#### Q. No. 8:-

- Scrape the details of Highest selling novels.
- Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare
- You have to find the following details:
    - Book name
    - Author name
    - Volumes sold
    - Publisher
    - Genre

In [26]:
# Loading the web driver

driver = webdriver.Chrome("chromedriver.exe")

In [27]:
# loading the web page

url8 = 'https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driver.get(url8)

In [34]:
# Creating empty lists

book_name = []
author_name = []
volumes_sold = []
publisher = []
genre_book = []

In [32]:
# Scraping the table data
data8 = []
data8_tag = driver.find_elements_by_xpath('//td[@class="left"]')
for d in data8_tag:
    try:
        data8.append(d.text)
    except NoSuchElementException:
        data8.append('--')
        
data8

['1',
 'Da Vinci Code,The',
 'Brown, Dan',
 '5,094,805',
 'Transworld',
 '2',
 'Harry Potter and the Deathly Hallows',
 'Rowling, J.K.',
 '4,475,152',
 'Bloomsbury',
 '3',
 "Harry Potter and the Philosopher's Stone",
 'Rowling, J.K.',
 '4,200,654',
 'Bloomsbury',
 '4',
 'Harry Potter and the Order of the Phoenix',
 'Rowling, J.K.',
 '4,179,479',
 'Bloomsbury',
 '5',
 'Fifty Shades of Grey',
 'James, E. L.',
 '3,758,936',
 'Random House',
 '6',
 'Harry Potter and the Goblet of Fire',
 'Rowling, J.K.',
 '3,583,215',
 'Bloomsbury',
 '7',
 'Harry Potter and the Chamber of Secrets',
 'Rowling, J.K.',
 '3,484,047',
 'Bloomsbury',
 '8',
 'Harry Potter and the Prisoner of Azkaban',
 'Rowling, J.K.',
 '3,377,906',
 'Bloomsbury',
 '9',
 'Angels and Demons',
 'Brown, Dan',
 '3,193,946',
 'Transworld',
 '10',
 "Harry Potter and the Half-blood Prince:Children's Edition",
 'Rowling, J.K.',
 '2,950,264',
 'Bloomsbury',
 '11',
 'Fifty Shades Darker',
 'James, E. L.',
 '2,479,784',
 'Random House',
 '12',
 'Twilight',
 'Meyer, Stephenie',
 '2,315,405',
 'Little, Brown Book',
 '13',
 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
 'Larsson, Stieg',
 '2,233,570',
 'Quercus',
 '14',
 'Fifty Shades Freed',
 'James, E. L.',
 '2,193,928',
 'Random House',
 '15',
 'Lost Symbol,The',
 'Brown, Dan',
 '2,183,031',
 'Transworld',
 '16',
 'New Moon',
 'Meyer, Stephenie',
 '2,152,737',
 'Little, Brown Book',
 '17',
 'Deception Point',
 'Brown, Dan',
 '2,062,145',
 'Transworld',
 '18',
 'Eclipse',
 'Meyer, Stephenie',
 '2,052,876',
 'Little, Brown Book',
 '19',
 'Lovely Bones,The',
 'Sebold, Alice',
 '2,005,598',
 'Pan Macmillan',
 '20',
 'Curious Incident of the Dog in the Night-time,The',
 'Haddon, Mark',
 '1,979,552',
 'Random House',
 '21',
 'Digital Fortress',
 'Brown, Dan',
 '1,928,900',
 'Transworld',
 '22',
 'Short History of Nearly Everything,A',
 'Bryson, Bill',
 '1,852,919',
 'Transworld',
 '23',
 'Girl Who Played with Fire,The:Millennium Trilogy',
 'Larsson, Stieg',
 '1,814,784',
 'Quercus',
 '24',
 'Breaking Dawn',
 'Meyer, Stephenie',
 '1,787,118',
 'Little, Brown Book',
 '25',
 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
 'Carle, Eric',
 '1,783,535',
 'Penguin',
 '26',
 'Gruffalo,The',
 'Donaldson, Julia',
 '1,781,269',
 'Pan Macmillan',
 '27',
 "Jamie's 30-Minute Meals",
 'Oliver, Jamie',
 '1,743,266',
 'Penguin',
 '28',
 'Kite Runner,The',
 'Hosseini, Khaled',
 '1,629,119',
 'Bloomsbury',
 '29',
 'One Day',
 'Nicholls, David',
 '1,616,068',
 'Hodder & Stoughton',
 '30',
 'Thousand Splendid Suns,A',
 'Hosseini, Khaled',
 '1,583,992',
 'Bloomsbury',
 '31',
 "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
 'Larsson, Stieg',
 '1,555,135',
 'Quercus',
 '32',
 "Time Traveler's Wife,The",
 'Niffenegger, Audrey',
 '1,546,886',
 'Random House',
 '33',
 'Atonement',
 'McEwan, Ian',
 '1,539,428',
 'Random House',
 '34',
 "Bridget Jones's Diary:A Novel",
 'Fielding, Helen',
 '1,508,205',
 'Pan Macmillan',
 '35',
 'World According to Clarkson,The',
 'Clarkson, Jeremy',
 '1,489,403',
 'Penguin',
 '36',
 "Captain Corelli's Mandolin",
 'Bernieres, Louis de',
 '1,352,318',
 'Random House',
 '37',
 'Sound of Laughter,The',
 'Kay, Peter',
 '1,310,207',
 'Random House',
 '38',
 'Life of Pi',
 'Martel, Yann',
 '1,310,176',
 'Canongate',
 '39',
 'Billy Connolly',
 'Stephenson, Pamela',
 '1,231,957',
 'HarperCollins',
 '40',
 'Child Called It,A',
 'Pelzer, Dave',
 '1,217,712',
 'Orion',
 '41',
 "Gruffalo's Child,The",
 'Donaldson, Julia',
 '1,208,711',
 'Pan Macmillan',
 '42',
 "Angela's Ashes:A Memoir of a Childhood",
 'McCourt, Frank',
 '1,204,058',
 'HarperCollins',
 '43',
 'Birdsong',
 'Faulks, Sebastian',
 '1,184,967',
 'Random House',
 '44',
 'Northern Lights:His Dark Materials S.',
 'Pullman, Philip',
 '1,181,503',
 'Scholastic Ltd.',
 '45',
 'Labyrinth',
 'Mosse, Kate',
 '1,181,093',
 'Orion',
 '46',
 'Harry Potter and the Half-blood Prince',
 'Rowling, J.K.',
 '1,153,181',
 'Bloomsbury',
 '47',
 'Help,The',
 'Stockett, Kathryn',
 '1,132,336',
 'Penguin',
 '48',
 'Man and Boy',
 'Parsons, Tony',
 '1,130,802',
 'HarperCollins',
 '49',
 'Memoirs of a Geisha',
 'Golden, Arthur',
 '1,126,337',
 'Random House',
 '50',
 "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
 'McCall Smith, Alexander',
 '1,115,549',
 'Little, Brown Book',
 '51',
 'Island,The',
 'Hislop, Victoria',
 '1,108,328',
 'Headline',
 '52',
 'PS, I Love You',
 'Ahern, Cecelia',
 '1,107,379',
 'HarperCollins',
 '53',
 'You are What You Eat:The Plan That Will Change Your Life',
 'McKeith, Gillian',
 '1,104,403',
 'Penguin',
 '54',
 'Shadow of the Wind,The',
 'Zafon, Carlos Ruiz',
 '1,092,349',
 'Orion',
 '55',
 'Tales of Beedle the Bard,The',
 'Rowling, J.K.',
 '1,090,847',
 'Bloomsbury',
 '56',
 'Broker,The',
 'Grisham, John',
 '1,087,262',
 'Random House',
 '57',
 "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
 'Atkins, Robert C.',
 '1,054,196',
 'Random House',
 '58',
 'Subtle Knife,The:His Dark Materials S.',
 'Pullman, Philip',
 '1,037,160',
 'Scholastic Ltd.',
 '59',
 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
 'Truss, Lynne',
 '1,023,688',
 'Profile Books Group',
 '60',
 "Delia's How to Cook:(Bk.1)",
 'Smith, Delia',
 '1,015,956',
 'Random House',
 '61',
 'Chocolat',
 'Harris, Joanne',
 '1,009,873',
 'Transworld',
 '62',
 'Boy in the Striped Pyjamas,The',
 'Boyne, John',
 '1,004,414',
 'Random House Childrens Books G',
 '63',
 "My Sister's Keeper",
 'Picoult, Jodi',
 '1,003,780',
 'Hodder & Stoughton',
 '64',
 'Amber Spyglass,The:His Dark Materials S.',
 'Pullman, Philip',
 '1,002,314',
 'Scholastic Ltd.',
 '65',
 'To Kill a Mockingbird',
 'Lee, Harper',
 '998,213',
 'Random House',
 '66',
 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
 'Gray, John',
 '992,846',
 'HarperCollins',
 '67',
 'Dear Fatty',
 'French, Dawn',
 '986,753',
 'Random House',
 '68',
 'Short History of Tractors in Ukrainian,A',
 'Lewycka, Marina',
 '986,115',
 'Penguin',
 '69',
 'Hannibal',
 'Harris, Thomas',
 '970,509',
 'Random House',
 '70',
 'Lord of the Rings,The',
 'Tolkien, J. R. R.',
 '967,466',
 'HarperCollins',
 '71',
 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
 'Moore, Michael',
 '963,353',
 'Penguin',
 '72',
 'Interpretation of Murder,The',
 'Rubenfeld, Jed',
 '962,515',
 'Headline',
 '73',
 'Sharon Osbourne Extreme:My Autobiography',
 'Osbourne, Sharon',
 '959,496',
 'Little, Brown Book',
 '74',
 'Alchemist,The:A Fable About Following Your Dream',
 'Coelho, Paulo',
 '956,114',
 'HarperCollins',
 '75',
 "At My Mother's Knee ...:and Other Low Joints",
 "O'Grady, Paul",
 '945,640',
 'Transworld',
 '76',
 'Notes from a Small Island',
 'Bryson, Bill',
 '931,312',
 'Transworld',
 '77',
 'Return of the Naked Chef,The',
 'Oliver, Jamie',
 '925,425',
 'Penguin',
 '78',
 'Bridget Jones: The Edge of Reason',
 'Fielding, Helen',
 '924,695',
 'Pan Macmillan',
 '79',
 "Jamie's Italy",
 'Oliver, Jamie',
 '906,968',
 'Penguin',
 '80',
 'I Can Make You Thin',
 'McKenna, Paul',
 '905,086',
 'Transworld',
 '81',
 'Down Under',
 'Bryson, Bill',
 '890,847',
 'Transworld',
 '82',
 'Summons,The',
 'Grisham, John',
 '869,671',
 'Random House',
 '83',
 'Small Island',
 'Levy, Andrea',
 '869,659',
 'Headline',
 '84',
 'Nigella Express',
 'Lawson, Nigella',
 '862,602',
 'Random House',
 '85',
 'Brick Lane',
 'Ali, Monica',
 '856,540',
 'Transworld',
 '86',
 "Memory Keeper's Daughter,The",
 'Edwards, Kim',
 '845,858',
 'Penguin',
 '87',
 'Room on the Broom',
 'Donaldson, Julia',
 '842,535',
 'Pan Macmillan',
 '88',
 'About a Boy',
 'Hornby, Nick',
 '828,215',
 'Penguin',
 '89',
 'My Booky Wook',
 'Brand, Russell',
 '820,563',
 'Hodder & Stoughton',
 '90',
 'God Delusion,The',
 'Dawkins, Richard',
 '816,907',
 'Transworld',
 '91',
 '"Beano" Annual,The',
 '0',
 '816,585',
 'D.C. Thomson',
 '92',
 'White Teeth',
 'Smith, Zadie',
 '815,586',
 'Penguin',
 '93',
 'House at Riverton,The',
 'Morton, Kate',
 '814,370',
 'Pan Macmillan',
 '94',
 'Book Thief,The',
 'Zusak, Markus',
 '809,641',
 'Transworld',
 '95',
 'Nights of Rain and Stars',
 'Binchy, Maeve',
 '808,900',
 'Orion',
 '96',
 'Ghost,The',
 'Harris, Robert',
 '807,311',
 'Random House',
 '97',
 'Happy Days with the Naked Chef',
 'Oliver, Jamie',
 '794,201',
 'Penguin',
 '98',
 'Hunger Games,The:Hunger Games Trilogy',
 'Collins, Suzanne',
 '792,187',
 'Scholastic Ltd.',
 '99',
 "Lost Boy,The:A Foster Child's Search for the Love of a Family",
 'Pelzer, Dave',
 '791,507',
 'Orion',
 '100',
 "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours",
 'Oliver, Jamie',
 '791,095',
 'Penguin']

In [35]:
# Scraping the book names
book_name = data8[1::5]

# Scraping the author names
author_name = data8[2::5]

# Scraping the Volumes sold
volumes_sold = data8[3::5]

# Scraping the Publishers of the books
publisher = data8[4::5]

# Printing the length of the columns
print(' Length of column Book name is ',len(book_name),'\n Lenth of coulmn Author name is',len(author_name),
       '\n Length of column Volumes sold is ',len(volumes_sold),'\n Length of column Publisher is ',len(publisher))

 Length of column Book name is  100
 Lenth of coulmn Author name is 100
 Length of column Volumes sold is  100
 Length of column Publisher is  100

In [36]:
# Scraping the Genre

gen_tag8 = driver.find_elements_by_xpath('//td[@class="last left"]')
for g in gen_tag8:
    try:
        genre_book.append(g.text)
    except NoSuchElementException:
        genre_book.append('--')
        
genre_book

['Crime, Thriller & Adventure',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Romance & Sagas',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 "Children's Fiction",
 'Romance & Sagas',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Romance & Sagas',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Popular Science',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Picture Books',
 'Picture Books',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Humour: Collections & General',
 'General & Literary Fiction',
 'Autobiography: General',
 'General & Literary Fiction',
 'Biography: The Arts',
 'Autobiography: General',
 'Picture Books',
 'Autobiography: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Science Fiction & Fantasy',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Fitness & Diet',
 'General & Literary Fiction',
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 'Fitness & Diet',
 'Young Adult Fiction',
 'Usage & Writing Guides',
 'Food & Drink: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Popular Culture & Media: General Interest',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Science Fiction & Fantasy',
 'Current Affairs & Issues',
 'Crime, Thriller & Adventure',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Travel Writing',
 'Food & Drink: General',
 'General & Literary Fiction',
 'National & Regional Cuisine',
 'Fitness & Diet',
 'Travel Writing',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Picture Books',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Popular Science',
 "Children's Annuals",
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Food & Drink: General',
 'Young Adult Fiction',
 'Biography: General',
 'Food & Drink: General']

In [37]:
len(genre_book)

100

In [38]:
# Creating the DataFrame

books = pd.DataFrame({'Book Name':book_name, 'Author Name':author_name, 'Volumes Sold':volumes_sold,
                      'Publisher':publisher, 'Genre':genre_book})

books

,Book Name,Author Name,Volumes Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

-------------------------------------------------------------------------------------------------------------------------------

#### Q. No. 9:-
- Scrape the details most watched tv series of all time from imdb.com.
- Url = https://www.imdb.com/list/ls095964455/
- You have to find the following details:
    - Name
    - Year span
    - Genre
    - Run time
    - Ratings
    - Votes

In [57]:
# Loading the web driver

driver=webdriver.Chrome("chromedriver.exe")

In [58]:
# loading the web page
url9 = 'https://www.imdb.com/list/ls095964455/'
driver.get(url9)

In [80]:
# Creating the empty lists

name_tv = []
year_span_tv = []
genre_tv = []
run_time_tv = []
ratings_tv = []
votes_tv = []

In [81]:
# Scraping the name of the top 100 most watched TV series

name_tag9 = driver.find_elements_by_xpath('//h3[@class="lister-item-header"]//a')
for n in name_tag9:
    try:
        name_tv.append(n.text)
    except NoSuchElementException:
        name_tv.append('--')
time.sleep(5)

# Scraping year span of the most watched top 100 TV Series

span_tag9 = driver.find_elements_by_xpath('//span[@class="lister-item-year text-muted unbold"]')
for s in span_tag9:
    try:
        year_span_tv.append(s.text)
    except NoSuchElementException:
        year_span_tv.append('--')
time.sleep(5)

# Scraping Genre of the top 100 most watched TV Series

genre_tag9 = driver.find_elements_by_xpath('//span[@class="genre"]')
for g in genre_tag9:
    try:
        genre_tv.append(g.text)
    except NoSuchElementException:
        genre_tv.append('--')
time.sleep(5)

# Scraping the run time

run_tag9 = driver.find_elements_by_xpath('//span[@class="runtime"]')
for r in run_tag9:
    try:
        run_time_tv.append(r.text)
    except NoSuchElementException:
        run_time_tv.append('--')
time.sleep(5)

# Scraping the ratings 

rating_tag9 = driver.find_elements_by_xpath('//div[@class="ipl-rating-star small"]')
for r9 in rating_tag9:
    try:
        ratings_tv.append(r9.text)
    except NoSuchElementException:
        ratings_tv.append('--')
time.sleep(5)

# Scraping the votes

vot_tag9 = driver.find_elements_by_xpath('//span[@name="nv"]')
for v in vot_tag9:
    try:
        votes_tv.append(v.text)
    except NoSuchElementException:
        votes_tv.append('--')
time.sleep(5)

#Printing the length of all the columns
print(len(name_tv),len(year_span_tv),len(genre_tv),len(run_time_tv),len(ratings_tv),len(votes_tv))

100 100 100 100 100 100

In [82]:
# Creating the DataFrame

tv = pd.DataFrame({'Name of TV Series':name_tv, 'Year Span':year_span_tv,'Genre':genre_tv, 
                  'Run Time':run_time_tv, 'Ratings':ratings_tv, 'Votes':votes_tv})

tv

,Name of TV Series,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,846,112"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"883,953"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"884,735"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"265,875"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"226,721"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"44,978"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"55,673"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8,"171,482"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"35,533"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"194,795"

------------------------------------------------------------------------------------------------------------------------------

#### Q. No. 10:-

- Details of Datasets from UCI machine learning repositories.
- Url = https://archive.ics.uci.edu/
- You have to find the following details:
    - Dataset name
    - Data type
    - Task
    - Attribute type
    - No of instances
    - No of attribute
    - Year
    
#### Note: - from the home page you have to go to the Show All Dataset page through code.

In [2]:
# Loading the web driver 

driver=webdriver.Chrome("chromedriver.exe")

In [3]:
# Loading the web page

url10 = 'https://archive.ics.uci.edu/'
driver.get(url10)

In [4]:
# Visiting 'View all dataset' page

view_tag10 = driver.find_element_by_xpath('/html/body/table[1]/tbody/tr/td[2]/span[2]/a')
view_tag10.click()

In [80]:
# Creating empty lists

dataset_name = []
data_type = []
task = []
attribute_type = []
instances = []
attribute_number = []
year_data = []

In [54]:
# Scraping the data 

data10 = []

dt_tag10 = driver.find_elements_by_xpath('//p[@class="normal"]')
for d10 in dt_tag10:
    if d10.text is None:
        data10.append('--')
    else:
        data10.append(d10.text)

data10 = data10[8:4623]
data10

['Abalone',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '4177 ',
 '8 ',
 '1995 ',
 'Adult',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '48842 ',
 '14 ',
 '1996 ',
 'Annealing',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '798 ',
 '38 ',
 ' ',
 'Anonymous Microsoft Web Data',
 ' ',
 'Recommender-Systems ',
 'Categorical ',
 '37711 ',
 '294 ',
 '1998 ',
 'Arrhythmia',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '452 ',
 '279 ',
 '1998 ',
 'Artificial Characters',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '6000 ',
 '7 ',
 '1992 ',
 'Audiology (Original)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '226 ',
 ' ',
 '1987 ',
 'Audiology (Standardized)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '226 ',
 '69 ',
 '1992 ',
 'Auto MPG',
 'Multivariate ',
 'Regression ',
 'Categorical, Real ',
 '398 ',
 '8 ',
 '1993 ',
 'Automobile',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer, Real ',
 '205 ',
 '26 ',
 '1987 ',
 'Badges',
 'Univariate, Text ',
 'Classification ',
 ' ',
 '294 ',
 '1 ',
 '1994 ',
 'Balance Scale',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '625 ',
 '4 ',
 '1994 ',
 'Balloons',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '16 ',
 '4 ',
 ' ',
 'Breast Cancer',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '286 ',
 '9 ',
 '1988 ',
 'Breast Cancer Wisconsin (Original)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '699 ',
 '10 ',
 '1992 ',
 'Breast Cancer Wisconsin (Prognostic)',
 'Multivariate ',
 'Classification, Regression ',
 'Real ',
 '198 ',
 '34 ',
 '1995 ',
 'Breast Cancer Wisconsin (Diagnostic)',
 'Multivariate ',
 'Classification ',
 'Real ',
 '569 ',
 '32 ',
 '1995 ',
 'Pittsburgh Bridges',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '108 ',
 '13 ',
 '1990 ',
 'Car Evaluation',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '1728 ',
 '6 ',
 '1997 ',
 'Census Income',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '48842 ',
 '14 ',
 '1996 ',
 'Chess (King-Rook vs. King-Knight)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Categorical, Integer ',
 ' ',
 '22 ',
 '1988 ',
 'Chess (King-Rook vs. King-Pawn)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '3196 ',
 '36 ',
 '1989 ',
 'Chess (King-Rook vs. King)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '28056 ',
 '6 ',
 '1994 ',
 'Chess (Domain Theories)',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Bach Chorales',
 'Univariate, Time-Series ',
 ' ',
 'Categorical, Integer ',
 '100 ',
 '6 ',
 ' ',
 'Connect-4',
 'Multivariate, Spatial ',
 'Classification ',
 'Categorical ',
 '67557 ',
 '42 ',
 '1995 ',
 'Credit Approval',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '690 ',
 '15 ',
 ' ',
 'Japanese Credit Screening',
 'Multivariate, Domain-Theory ',
 'Classification ',
 'Categorical, Real, Integer ',
 '125 ',
 ' ',
 '1992 ',
 'Computer Hardware',
 'Multivariate ',
 'Regression ',
 'Integer ',
 '209 ',
 '9 ',
 '1987 ',
 'Contraceptive Method Choice',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '1473 ',
 '9 ',
 '1997 ',
 'Covertype',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '581012 ',
 '54 ',
 '1998 ',
 'Cylinder Bands',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '512 ',
 '39 ',
 '1995 ',
 'Dermatology',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '366 ',
 '33 ',
 '1998 ',
 'Diabetes',
 'Multivariate, Time-Series ',
 ' ',
 'Categorical, Integer ',
 ' ',
 '20 ',
 ' ',
 'DGP2 - The Second Data Generation Program',
 'Data-Generator ',
 ' ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Document Understanding',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1994 ',
 'EBL Domain Theories',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Echocardiogram',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '132 ',
 '12 ',
 '1989 ',
 'Ecoli',
 'Multivariate ',
 'Classification ',
 'Real ',
 '336 ',
 '8 ',
 '1996 ',
 'Flags',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '194 ',
 '30 ',
 '1990 ',
 'Function Finding',
 ' ',
 'Function-Learning ',
 'Real ',
 '352 ',
 ' ',
 '1990 ',
 'Glass Identification',
 'Multivariate ',
 'Classification ',
 'Real ',
 '214 ',
 '10 ',
 '1987 ',
 "Haberman's Survival",
 'Multivariate ',
 'Classification ',
 'Integer ',
 '306 ',
 '3 ',
 '1999 ',
 'Hayes-Roth',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '160 ',
 '5 ',
 '1989 ',
 'Heart Disease',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '303 ',
 '75 ',
 '1988 ',
 'Hepatitis',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '155 ',
 '19 ',
 '1988 ',
 'Horse Colic',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '368 ',
 '27 ',
 '1989 ',
 'ICU',
 'Multivariate, Time-Series ',
 ' ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Image Segmentation',
 'Multivariate ',
 'Classification ',
 'Real ',
 '2310 ',
 '19 ',
 '1990 ',
 'Internet Advertisements',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '3279 ',
 '1558 ',
 '1998 ',
 'Ionosphere',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '351 ',
 '34 ',
 '1989 ',
 'Iris',
 'Multivariate ',
 'Classification ',
 'Real ',
 '150 ',
 '4 ',
 '1988 ',
 'ISOLET',
 'Multivariate ',
 'Classification ',
 'Real ',
 '7797 ',
 '617 ',
 '1994 ',
 'Kinship',
 'Relational ',
 'Relational-Learning ',
 'Categorical ',
 '104 ',
 '12 ',
 '1990 ',
 'Labor Relations',
 'Multivariate ',
 ' ',
 'Categorical, Integer, Real ',
 '57 ',
 '16 ',
 '1988 ',
 'LED Display Domain',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Categorical ',
 ' ',
 '7 ',
 '1988 ',
 'Lenses',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '24 ',
 '4 ',
 '1990 ',
 'Letter Recognition',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '20000 ',
 '16 ',
 '1991 ',
 'Liver Disorders',
 'Multivariate ',
 ' ',
 'Categorical, Integer, Real ',
 '345 ',
 '7 ',
 '1990 ',
 'Logic Theorist',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Lung Cancer',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '32 ',
 '56 ',
 '1992 ',
 'Lymphography',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '148 ',
 '18 ',
 '1988 ',
 'Mechanical Analysis',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '209 ',
 '8 ',
 '1990 ',
 'Meta-data',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '528 ',
 '22 ',
 '1996 ',
 'Mobile Robots',
 'Domain-Theory ',
 ' ',
 'Categorical, Integer, Real ',
 ' ',
 ' ',
 '1995 ',
 'Molecular Biology (Promoter Gene Sequences)',
 'Sequential, Domain-Theory ',
 'Classification ',
 'Categorical ',
 '106 ',
 '58 ',
 '1990 ',
 'Molecular Biology (Protein Secondary Structure)',
 'Sequential ',
 'Classification ',
 'Categorical ',
 '128 ',
 ' ',
 ' ',
 'Molecular Biology (Splice-junction Gene Sequences)',
 'Sequential, Domain-Theory ',
 'Classification ',
 'Categorical ',
 '3190 ',
 '61 ',
 '1992 ',
 "MONK's Problems",
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '432 ',
 '7 ',
 '1992 ',
 'Moral Reasoner',
 'Domain-Theory ',
 ' ',
 ' ',
 '202 ',
 ' ',
 '1994 ',
 'Multiple Features',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '2000 ',
 '649 ',
 ' ',
 'Mushroom',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '8124 ',
 '22 ',
 '1987 ',
 'Musk (Version 1)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '476 ',
 '168 ',
 '1994 ',
 'Musk (Version 2)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '6598 ',
 '168 ',
 '1994 ',
 'Nursery',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '12960 ',
 '8 ',
 '1997 ',
 'Othello Domain Theory',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1991 ',
 'Page Blocks Classification',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '5473 ',
 '10 ',
 '1995 ',
 'Optical Recognition of Handwritten Digits',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '5620 ',
 '64 ',
 '1998 ',
 'Pen-Based Recognition of Handwritten Digits',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '10992 ',
 '16 ',
 '1998 ',
 'Post-Operative Patient',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '90 ',
 '8 ',
 '1993 ',
 'Primary Tumor',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '339 ',
 '17 ',
 '1988 ',
 'Prodigy',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Qualitative Structure Activity Relationships',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Quadruped Mammals',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 ' ',
 '72 ',
 '1992 ',
 'Servo',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer ',
 '167 ',
 '4 ',
 '1993 ',
 'Shuttle Landing Control',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '15 ',
 '6 ',
 '1988 ',
 'Solar Flare',
 'Multivariate ',
 'Regression ',
 'Categorical ',
 '1389 ',
 '10 ',
 '1989 ',
 'Soybean (Large)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '307 ',
 '35 ',
 '1988 ',
 'Soybean (Small)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '47 ',
 '35 ',
 '1987 ',
 'Challenger USA Space Shuttle O-Ring',
 'Multivariate ',
 'Regression ',
 'Integer ',
 '23 ',
 '4 ',
 '1993 ',
 'Low Resolution Spectrometer',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '531 ',
 '102 ',
 '1988 ',
 'Spambase',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '4601 ',
 '57 ',
 '1999 ',
 'SPECT Heart',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '267 ',
 '22 ',
 '2001 ',
 'SPECTF Heart',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '267 ',
 '44 ',
 '2001 ',
 'Sponge',
 'Multivariate ',
 'Clustering ',
 'Categorical, Integer ',
 '76 ',
 '45 ',
 ' ',
 'Statlog Project',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1992 ',
 'Student Loan Relational',
 'Domain-Theory ',
 ' ',
 ' ',
 '1000 ',
 ' ',
 '1993 ',
 'Teaching Assistant Evaluation',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '151 ',
 '5 ',
 '1997 ',
 'Tic-Tac-Toe Endgame',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '958 ',
 '9 ',
 '1991 ',
 'Thyroid Disease',
 'Multivariate, Domain-Theory ',
 'Classification ',
 'Categorical, Real ',
 '7200 ',
 '21 ',
 '1987 ',
 'Trains',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '10 ',
 '32 ',
 '1994 ',
 'University',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '285 ',
 '17 ',
 '1988 ',
 'Congressional Voting Records',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '435 ',
 '16 ',
 '1987 ',
 'Water Treatment Plant',
 'Multivariate ',
 'Clustering ',
 'Integer, Real ',
 '527 ',
 '38 ',
 '1993 ',
 'Waveform Database Generator (Version 1)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 '5000 ',
 '21 ',
 '1988 ',
 'Waveform Database Generator (Version 2)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 '5000 ',
 '40 ',
 '1988 ',
 'Wine',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '178 ',
 '13 ',
 '1991 ',
 'Yeast',
 'Multivariate ',
 'Classification ',
 'Real ',
 '1484 ',
 '8 ',
 '1996 ',
 'Zoo',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '101 ',
 '17 ',
 '1990 ',
 'Undocumented',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Twenty Newsgroups',
 'Text ',
 ' ',
 ' ',
 '20000 ',
 ' ',
 '1999 ',
 'Australian Sign Language signs',
 'Multivariate, Time-Series ',
 'Classification ',
 'Categorical, Real ',
 '6650 ',
 '15 ',
 '1999 ',
 'Australian Sign Language signs (High Quality)',
 'Multivariate, Time-Series ',
 'Classification ',
 'Real ',
 '2565 ',
 '22 ',
 '2002 ',
 'US Census Data (1990)',
 'Multivariate ',
 'Clustering ',
 'Categorical ',
 '2458285 ',
 '68 ',
 ' ',
 'Census-Income (KDD)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '299285 ',
 '40 ',
 '2000 ',
 'Coil 1999 Competition Data',
 'Multivariate ',
 ' ',
 'Categorical, Real ',
 '340 ',
 '17 ',
 '1999 ',
 'Corel Image Features',
 'Multivariate ',
 ' ',
 'Real ',
 '68040 ',
 '89 ',
 '1999 ',
 'E. Coli Genes',
 'Relational ',
 ' ',
 ' ',
 ' ',
 ' ',
 '2001 ',
 'EEG Database',
 'Multivariate, Time-Series ',
 ' ',
 'Categorical, Integer, Real ',
 '122 ',
 '4 ',
 '1999 ',
 'El Nino',
 'Spatio-temporal ',
 ' ',
 'Integer, Real ',
 '178080 ',
 '12 ',
 '1999 ',
 'Entree Chicago Recommendation Data',
 'Transactional, Sequential ',
 'Recommender-Systems ',
 'Categorical ',
 '50672 ',
 ' ',
 '2000 ',
 'CMU Face Images',
 'Image ',
 'Classification ',
 'Integer ',
 '640 ',
 ' ',
 '1999 ',
 'Insurance Company Benchmark (COIL 2000)',
 'Multivariate ',
 'Regression, Description ',
 'Categorical, Integer ',
 '9000 ',
 '86 ',
 '2000 ',
 'Internet Usage Data',
 'Multivariate ',
 ' ',
 'Categorical, Integer ',
 '10104 ',
 '72 ',
 '1999 ',
 'IPUMS Census Database',
 'Multivariate ',
 ' ',
 'Categorical, Integer ',
 '256932 ',
 '61 ',
 '1999 ',
 'Japanese Vowels',
 'Multivariate, Time-Series ',
 'Classification ',
 'Real ',
 '640 ',
 '12 ',
 ' ',
 'KDD Cup 1998 Data',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer ',
 '191779 ',
 '481 ',
 '1998 ',
 'KDD Cup 1999 Data',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '4000000 ',
 '42 ',
 '1999 ',
 'M. Tuberculosis Genes',
 'Relational ',
 ' ',
 ' ',
 ' ',
 ' ',
 '2001 ',
 'Movie',
 'Multivariate, Relational ',
 ' ',
 ' ',
 '10000 ',
 ' ',
 '1999 ',
 'MSNBC.com Anonymous Web Data',
 'Sequential ',
 ' ',
 'Categorical ',
 '989818 ',
 ' ',
 ' ',
 'NSF Research Award Abstracts 1990-2003',
 'Text ',
 ' ',
 ' ',
 '129000 ',
 ' ',
 '2003 ',
 'Pioneer-1 Mobile Robot Data',
 'Multivariate, Time-Series ',
 ' ',
 'Categorical, Real ',
 ' ',
 ' ',
 '1999 ',
 'Pseudo Periodic Synthetic Time Series',
 'Univariate, Time-Series ',
 ' ',
 ' ',
 '100000 ',
 ' ',
 '1999 ',
 'Reuters-21578 Text Categorization Collection',
 'Text ',
 'Classification ',
 'Categorical ',
 '21578 ',
 '5 ',
 '1997 ',
 'Robot Execution Failures',
 'Multivariate, Time-Series ',
 'Classification ',
 'Integer ',
 '463 ',
 '90 ',
 '1999 ',
 'Synthetic Control Chart Time Series',
 'Time-Series ',
 'Classification, Clustering ',
 'Real ',
 '600 ',
 ' ',
 '1999 ',
 'Syskill and Webert Web Page Ratings',
 'Multivariate, Text ',
 'Classification ',
 'Categorical ',
 '332 ',
 '5 ',
 '1998 ',
 'UNIX User Data',
 'Text, Sequential ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Volcanoes on Venus - JARtool experiment',
 'Image ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Statlog (Australian Credit Approval)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '690 ',
 '14 ',
 ' ',
 'Statlog (German Credit Data)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '1000 ',
 '20 ',
 '1994 ',
 'Statlog (Heart)',
 'Multivariate ',
 'Classification ',
 'Categorical, Real ',
 '270 ',
 '13 ',
 ...]

In [81]:
# Scraping dataset name
data_name = data10[0::7]
data_name = data_name[:588]
data_name

# Scraping data type
data_type = data10[1::7]
data_type = data_type[:588]
data_type

# Scrpaing task
task = data10[2::7]
task

# Scraping Attribute type
attribute_type = data10[3::7]
attribute_type

# Scraping No of instances
instances = data10[4::7]
instances

# Scraping No of attribute
attribute_number = data10[5::7]
attribute_number

# Scraping Year
year_data = data10[6::7]
year_data

print(len(data_name),len(data_type),len(task),len(attribute_type),len(instances),len(attribute_number),len(year_data))

588 588 588 588 588 588 588

In [82]:
# Creating dataframe

dataset = pd.DataFrame({'Dataset Name':data_name, 'Data Type':data_type, 'Task':task, 
                        'Attribute Type':attribute_type, 'Number of Instances':instances, 
                        'Number of Attribute':attribute_number, 'Year':year_data})

dataset

,Dataset Name,Data Type,Task,Attribute Type,Number of Instances,Number of Attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021